#+title: "怪物猎人RISE"入门学习
#+date: 2021-03-30
#+index: "怪物猎人RISE"入门学习
#+tags: Game
#+begin_abstract
balabala
#+end_abstract

*** 为什么需要学习

在"怪物猎人"里面变强并不是让角色成长,而是需要玩家成长.

成长分两个方面,已是对游戏内内容的了解和理解,以及操作熟练度.

怪物猎人里面的内容十分多,有很多概念需要理解,

*** 一些入门概念

**** 纳刀态与持刀态

     角色没有手持武器时的状态就叫做纳刀态,否者叫做持刀态.

     角色处于纳刀态时,移动速度会很快,可以变换到这个状态进行走位远离敌人来进行躲避或者做一些耗时比较长的行为.

**** 自由态以及连携态

     (网络上没有找到比较靠谱的解析,因此这里是我在看了各个说法之后的理解)

     这概念需要我们先理解怪物猎人里面的动作状态机如何工作的.

     一个招式由1到多个动作按照一定顺序组成,每个动作都需要角色在规定状态下,在规定时间内进行规定的输入才能触发,也就是说一个招式就是一条输入规则,

     一套输入规则叫做出招表,准确来说就是一套状态机规则.

     \\

     比如 $X \rightarrow X \rightarrow X$ 就是其中一个招式,我们暂且叫它"基本连段"吧.

     按下第一次 $X$ 后会有一个动作,这里也给它一个名字"连段1",一个动作实际上是一段动画,

     在这段动画播放的 *某个时间段内* 按下第 2 次 $X$ 就会触发另外一个动作"连段2",我们把从一个动作到下一个动作叫做 *派生*,

     我们姑且先把这个时间段称作 *输入时机*,在输入时机之外的任何输入,以及输入时机之内的任何无法派生出下一个动作的输入都会被无视.

     同样在"连段2"结束前按下第 3 次 $X$ 后会派生出最后一个动作"连段3",等最后一个动作结束了,招式才能算完成,也就进入了 *招式结束* 的状态.

     这是完整使用招式的正常过程,还有因为一些原因(没有进入正确,受到敌人攻击)无法成功派生出下一个动作而提前进入招式结束状态,这种叫做 *招式中断*.

     不过有时候中断招式可以是玩家故意的,因为在没有进入 *招式结束* 状态时, *规则之外的任何输入都是无效的*,

     如果在使用招式时发现敌人马上要攻击过来了,想走位躲避,或者想使用另外一个招式进行格挡,但是这两个招式又无法衔接上,那么没办法,只能吃下这攻击.

     我们把这种处于使用招式中的状态叫做 *连携态*; 在连携态之外的时间内,角色都处于 *自由态*,这状态下角色可以使用任何招式,也可以把它理解为待出招状态.

     什么时候进入连携态,什么时候进入自由态则需要玩家根据怪物的行为和角色状态进行判断,只有对怪物越了解,对自己的武器性能越了解,时机的选择才能更好.

**** 动作值

每一个动作都有自己的伤害大小,这个就是动作指.


**** Guard Point

简称 =GP=,可以理解为完美防御,或者瞬间防御.

招式动作里面有几帧让角色处于无敌状态,这个状态下可以抵消掉角色受到的 *一次* 攻击,

同时保持动作 *减少变形* 或者说减少收到伤害的硬直,减少的程度受到防御性能影响.

我们会把这种情况说是"把攻击 =GP= 掉",如果硬直很小,角色还能够快速派生招式.

注意,是一次 =GP= 只能抵消一次攻击,想抵消多段攻击需要进行多次 =GP=.

因为 =GP= 一次会消耗耐力,耐力不足会 =GP= 失败,所以面对多段攻击最好选择走位躲避,

当然耐力的消耗也会受到防御性能的影响.

只有部分武器拥有 =GP= 机制.基本上带盾的武器都有这种机制,盾斧就是一把"通过GP进行快速反击怪物"为卖点的武器.

*怪物AI研究*



**** 斩味

武器锋利度



*** 武器

**** 盾斧


*** 进阶

学习/分析怪物机制,拆解怪物的AI以及研究如何应对处理.
