#+title: "怪物猎人RISE"入门学习
#+date: 2021-03-30
#+index: "怪物猎人RISE"入门学习
#+tags: Game
#+begin_abstract
balabala
#+end_abstract

*** 为什么需要学习

在"怪物猎人"里面变强并不是让角色成长,而是需要玩家成长.

成长分两个方面,已是对游戏内内容的了解和理解,以及操作熟练度.

怪物猎人里面的内容十分多,有很多概念需要理解,


*** 一些入门概念

**** 关于按键输入

     虽然说日常打惯了字,但是我们很少关心按键的过程.

     不论是键盘还是手柄,想要成功输入就需要物理上把按键压(press)到一定程度,这个程度叫做键程(没有找到很官方的说明).

     每个键盘或手柄的键程都不一样,刚好达到成功输入的程度叫做最低键程,触底的程度叫做触底键程.

     在进行连续的快速输入时,很容易会出现按得不到位而没有成功输入的情况,因此最好熟悉你的键盘或手柄的键程,或者养成按到触底的习惯.

     就算成功输入,到输入触发也需要一段时间的,输入设备是在一遍又一遍地检查用户是否在输入,输入了什么,也就是轮询(polling),单位时间内轮询的次数叫做轮询率(polling rate),

     轮询率越高,输入的触发速度越快,轮询率越低就越有延迟感.摇杆也是一个道理.

     为什么我们要关心这些,因为怪物猎人对输入时机的把握要求还是比较高的,我们必须明白 =Swtich= 版的 "怪物猎人:崛起" 会有一点输入延迟,

     想要在某个时机使用某个招式,必须要提前一小段时间.

**** 纳刀态与持刀态

     角色没有手持武器时的状态就叫做纳刀态,否者叫做持刀态.

     角色处于纳刀态时,移动速度会很快,可以变换到这个状态进行走位远离敌人来进行躲避或者做一些耗时比较长的行为.

**** 自由态以及连携态

     (网络上没有找到比较靠谱的解析,因此这里是我在看了各个说法之后的理解)

     这概念需要我们先理解怪物猎人里面的动作状态机如何工作的.

     一个招式由1到多个动作按照一定顺序组成,每个动作都需要角色在规定状态下,在规定时间内进行规定的输入才能触发,也就是说一个招式就是一条输入规则,

     一套输入规则叫做出招表,准确来说就是一套状态机规则.

     \\

     比如 $X \rightarrow X \rightarrow X$ 就是其中一个招式,我们暂且叫它"基本连段"吧.

     按下第一次 $X$ 后会有一个动作,这里也给它一个名字"连段1",一个动作实际上是一段动画,

     在这段动画播放的 *某个时间段内* 按下第 2 次 $X$ 就会触发另外一个动作"连段2",我们把从一个动作到下一个动作叫做 *派生*,

     我们姑且先把这个时间段称作 *输入时机*,在输入时机之外的任何输入,以及输入时机之内的任何无法派生出下一个动作的输入都会被无视.

     同样在"连段2"结束前按下第 3 次 $X$ 后会派生出最后一个动作"连段3",等最后一个动作结束了,招式才能算完成,也就进入了 *招式结束* 的状态.

     这是完整使用招式的正常过程,还有因为一些原因(没有进入正确,受到敌人攻击)无法成功派生出下一个动作而提前进入招式结束状态,这种叫做 *招式中断*.

     不过有时候中断招式可以是玩家故意的,因为在没有进入 *招式结束* 状态时, *规则之外的任何输入都是无效的*,

     如果在使用招式时发现敌人马上要攻击过来了,想走位躲避,或者想使用另外一个招式进行格挡,但是这两个招式又无法衔接上,那么没办法,只能吃下这攻击.

     我们把这种处于使用招式中的状态叫做 *连携态*; 在连携态之外的时间内,角色都处于 *自由态*,这状态下角色可以使用任何招式,也可以把它理解为待出招状态.

     什么时候进入连携态,什么时候进入自由态则需要玩家根据怪物的行为和角色状态进行判断,只有对怪物越了解,对自己的武器性能越了解,时机的选择才能更好.

**** 动作值

每一个动作都有自己的伤害大小,这个就是动作指.

**** Guard Point

简称 =GP=,可以理解为完美防御,或者瞬间防御.

招式动作里面有几帧让角色处于无敌状态,这个状态下可以抵消掉角色受到的 *一次* 攻击,

同时保持动作 *减少变形* 或者说减少收到伤害的硬直,减少的程度受到防御性能影响.

我们会把这种情况说是"把攻击 =GP= 掉",如果硬直很小,角色还能够快速派生招式.

注意,是一次 =GP= 只能抵消一次攻击,想抵消多段攻击需要进行多次 =GP=.

因为 =GP= 一次会消耗耐力,耐力不足会 =GP= 失败,所以面对多段攻击最好选择走位躲避,

当然耐力的消耗也会受到防御性能的影响.

只有部分武器拥有 =GP= 机制.基本上带盾的武器都有这种机制,盾斧就是一把"通过GP进行快速反击怪物"为卖点的武器.

*怪物AI研究*


**** 斩味

武器锋利度



*** 武器

**** 盾斧(Charge blade)

     盾斧是一把拥有剑模式和斧模式两种模式的武器,并且拥有一套能量机制.

     # 补充剑模式和斧模式的图,以及能量瓶图标.

     在不考虑额外因素情况下,能量瓶的能量 *主要* 来源是通过剑模式的攻击进行积累,

     通过瓶子的图标可以看到能量的积累程度,一共有四种: 白,黄,红和红色闪光,分别对应"零","少量","满"以及"过载".

     # 补充能量瓶图标

     要使用积累的能量,需要先把能量填充进瓶子里面,俗称"装瓶",这个时候能量瓶的图标就发生改变,瓶子由空心变实心.

     在能量过载的时候,剑在一般模式下攻击会出现弹刀情况,因此注意及时装瓶.

     而装好的瓶子只能由斧模式的招式使用.

     所以总体下来盾斧的一套使用流程就是以剑模式的招式负责收集能量,以斧模式的招式使用能量.
     

***** 基本操作

      一. 剑模式

剑模式下的攻击(下面检测剑攻击)可以为武器充能

能量(瓶子图标)分黄色和红色两种

全红就说明能量过多,此时剑攻击强制弹刀

能量需要填充(也叫装瓶,瓶子叫做能量瓶)才能在后续使用,填充后瓶子的图标也会发生改变,瓶子图标变成白色实心,并且剑攻击的弹刀解除

得到的实心瓶数量由填充时的能量颜色决定,黄色3个,红色5个

具体操作是剑模式下 ZR+A

剑基本操作

-> 表示下一个指令

+ 表示两个指令一起按,比如 x+a 就是x键和a键一起按,这里的一起按并不要求在同一个时间点按下(当然也可以这么做),而是指最终一起按住,比方说这例子,可以先按住x再按住a,注意两个按键之间时间间隔不能太长,并且要注意到一个事实:技能的发动时间就在a按下之后

= 表示最后得到的动作

(收刀时)推动左摇杆+x = 剑(拔刀)突进斩

(持刀时)x+a = 剑突进斩

剑突进斩可以在与魔物稍有距离作为起手技能

x(剑牵制斩) -> x(剑回斩) -> x(剑回旋斩)

翻滚后 -> x = 剑回斩

长按a后到合适时候松开 = 蓄力二连斩

蓄力二连斩 -> x = 剑回旋斩

任意剑攻击后 -> 推动左摇杆+a = 剑移动斩

任意剑攻击后 -> x+a = 盾突刺

剑移动斩的后摇会比较大,可以使用盾突刺或者翻滚(b)来取消后摇,这两个动作的后摇比较小

任意剑攻击后 -> 左右推动左摇杆+b = 左右垫步

垫步 -> x = 剑回旋斩

ZR = 举盾

ZR+X = 剑变形斩,变形斩后武器进入斧模式

攒能量的思路

1.(可循环)蓄力二连斩 -> 剑回旋斩
2.(可循环)蓄力二连斩 -> 盾突刺 -> 蓄力二连斩

二. 斧模式

基本操作

(收刀时)ZR = 直接进入斧模式,并且进行(拔刀)突进敲打

(持刀时)ZR = 斧变形斩,然后进入剑模式

推动左摇杆+x = 突进敲打

x = 斧上捞斩

斧上捞斩 -> x = 斧下斩

突进敲打 -> x(斧上捞斩) -> x(斧下斩)

x+a = 高压力属性解放斩(也就是俗话的大解),然后进入剑模式

在剑模式的盾突刺后可以直接接高压力属性解放斩

斧模式下a(属性解放斩,俗称一解) -> a(属性解放斩二,俗称二解) -> a(高出力属性解放斩,俗称大解) -> 进入剑模式

三. 能量使用

介绍如何使用填充好的瓶子

能量有两种用途进入属性强化状态(红盾)和剑强化状态(红剑)

红盾可提高斧模式的输出和盾牌防御,并且解放高威力攻击动作

开红盾的操作

在大解抬手的过程ZR = 取消大解,给盾牌进行充能

充能需要消耗所有能量瓶,瓶子数量和维持红盾状态时间有关,因此最好在满能量下开红盾

红剑可以提高剑模式的输出,并且不会再弹刀

在红盾时ZR+A填充动作(可以没有瓶子)起手时 -> 按住x一直等到等填充进去时再松开 = 剑高压属性斩

解放的动作

有红盾的时候进行高出力属性斩 = 超高出力属性解放斩,俗称超解

在超高出力属性解放斩抬手时(发电机轰隆响得时候),往人物的后方向推动摇杆+x = 高出力属性解放斩


四. 常用连招和派生

斧模式下,突进敲打 -> a = 属性解放斩2

斧模式下,斧上捞斩 -> a = 属性解放斩2

斧模式下,斧下斩 -> a = 属性解放斩

(rise新增)斧模式下,斧上捞斩 -> x+a = 高出力属性解放斩

斧模式任意攻击 -> x+a = 高出力属性解放斩

剑模式下,垫步和剑移动斩可以无限循环,也就是任何剑攻击后 -> (往角色左或右方向推动摇杆+b -> 往任意方向推动摇杆+a)循环

又或者,任何剑攻击后 -> (往任意方向推动摇杆+a -> 往角色左或右方向推动摇杆+b)循环

剑模式下,任何剑攻击后 -> 往角色背后方向拉到摇杆+a -> x+a（盾突刺）-> x+a(高出力属性解放斩)

(在接盾突刺前可以稍微调整方向?)

五. GP机制


*** 进阶

学习/分析怪物机制,拆解怪物的AI以及研究如何应对处理.
