#+title: "怪物猎人RISE"入门学习
#+date: 2021-03-30
#+index: "怪物猎人RISE"入门学习
#+tags: Game
#+begin_abstract
balabala
#+end_abstract

*** 为什么需要学习

在"怪物猎人"里面变强并不是让角色成长,而是需要玩家成长.

成长分两个方面,已是对游戏内内容的了解和理解,以及操作熟练度.

怪物猎人里面的内容十分多,有很多概念需要理解,

*** 一些入门概念

*持刀态*

*纳刀态*

*自由态*

(网络上没有找到比较靠谱的解析,因此这里是我在看了各个说法之后的理解)

这概念需要我们先理解怪物猎人里面的动作状态机如何工作的.

一个招式由1到多个动作按照一定顺序组成,每个动作都需要玩家在规定状态下以及规定时间内进行规定的输入才能触发,也就是说一个招式就是一条输入规则,

一套输入规则叫做出招表,准确来说就是一套状态机规则.

比如 $X \rightarrow X \rightarrow X$ 就是其中一个招式,我们暂且叫它"基本连段"吧.

按下第一次 $X$ 后会有一个动作,这里也给它一个名字"连段1",一个动作实际上是一段动画,

在这段动画播放结束之前按下第 2 次 $X$ 就会触发另外一个动作"连段2",我们把从一个动作到下一个动作叫做 *派生*,

在动画时间期间,任何无法派出下一个生动作的输入都会被无视.

同样在"连段2"这个动画播放结束前按下第 3 次 $X$ 后会派生出最后一个动作"连段3",等最后一个动作结束了,招式才能算完成,也就进入了 *招式结束* 的状态.

人总有出错的时候,有时候会无法在动画时间内进行正确的输入,我们把这种情况叫做 *招式中断*.

不过有时候中断招式可以是故意的,因为在没有进入 *招式结束* 或 *招式中断* 状态时,规则之外的任何输入都是无效的,

特别是有些招式的一些动作的动画时间是非常长的,所以有时候需要采取 *招式中断* 避免进入该动作.

避免进入动画时间长的动作还可以选择一些别的别的可衔接招式来取代原本要派生的动作,当然这要建立在有这种招式的强前提下,

比方说"连段3"是一段很长时间的 =pose= 动画,这导致角色容易收到敌人攻击,

而这个时候恰好有一个招式是在任意"连段"动作时输入 $B$ 可以进行翻滚,而翻滚的动画时间比"连段3"的更短,并且还能在翻滚时衔接一些不错的招式,

那必须毫不犹豫地选择翻滚.

我们把 *招式结束* 和 *招式中断* 这种可以进行任意招式的第一个输入的状态叫做自由态.

或者这么理解,自由态就是角色没有在进行任何招式,随时都能使用招式的一种状态,简单点就是待出招状态.

*斩味*

武器锋利度

*动作值*

*** 武器

**** 盾斧
