#+title: "怪物猎人RISE"入门学习
#+date: 2021-03-30
#+index: "怪物猎人RISE"入门学习
#+status: wd
#+tags: Game
#+begin_abstract
balabala
#+end_abstract

*** 为什么需要学习

在"怪物猎人"里面变强并不是让角色成长,而是需要玩家成长.

成长分两个方面,已是对游戏内内容的了解和理解,以及操作熟练度.

怪物猎人里面的内容十分多,有很多概念需要理解,


*** 一些入门概念

**** 关于按键输入

     虽然说日常打惯了字,但是我们很少关心按键的过程.

     就那打字的这个动作来说,简单来说就是按下按键,机器检测到按键被按下,告诉某个程序是哪个按键被按下了,程序根据这个消息进行处理,把处理结果显示在屏幕上.

     我们暂且把按下按键的动作叫做输入,把输入的内容(也就是哪个按键)叫做指令.

     不论是键盘还是手柄,想要让机器检测到按键被按下,那么就需要物理上把按键压(press)到一定程度,这个程度叫做键程(没有找到很官方的说明).

     每个键盘或手柄的键程都不一样,刚好达到"能够检测到的程度"叫做最低键程,触底的程度叫做触底键程.

     在进行连续的快速输入时,很容易会出现按得不到位而没有被检测到的情况,因此最好熟悉你的键盘或手柄的键程,或者养成按到触底的习惯.

     就算达到了"检测到"的键程,但实际上机器能够检测得到也是需要一点时间的,输入设备是在一遍又一遍地检查用户是否在输入,输入了什么,也就是轮询(polling),单位时间内轮询的次数叫做轮询率(polling rate),

     轮询率越高,输入的触发速度越快,轮询率越低就越有延迟感,摇杆也是一个道理,当然这个时间是很短的,人很难察觉得到,所以这点延迟基本上可以不算.

     另外一种延迟是由处理指令的程序有意或无意造成的,程序接收到了指令,处理指令会需要一点时间,再把结果反馈到屏幕上.

     为什么我们要关心这些,因为"怪物猎人"有些操作对输入时机的把握要求还是比较高的,后面会讲到的 =GP= 就是这样.

     我们需要知道一个事实: =Swtich= 版的"怪物猎人:崛起"会有一点输入延迟,而且据我感觉大部份的延迟时间应该是来自于游戏本身,

     这个延迟不能说很长,但还是能感觉出来的,特别是对 =GP= 这种吃时机的操作来说.


**** 纳刀态与持刀态

     角色没有手持武器时的状态就叫做纳刀态,否者叫做持刀态.

     角色处于纳刀态时,移动速度会很快,可以变换到这个状态进行走位远离敌人来进行躲避或者做一些耗时比较长的行为.


**** 自由态以及连携态

     (网络上没有找到比较靠谱的解析,因此这里是我在看了各个说法之后的理解)

     这概念需要我们先理解怪物猎人里面的动作状态机如何工作的.

     一个招式由1到多个动作按照一定顺序组成,每个动作都需要角色在规定状态下,在规定时间内进行规定的输入才能触发,也就是说一个招式就是一条输入规则,

     一套输入规则叫做出招表,准确来说就是一套状态机规则.

     \\

     比如 $X \rightarrow X \rightarrow X$ 就是其中一个招式,我们暂且叫它"基本连段"吧.

     按下第一次 $X$ 后会有一个动作,这里也给它一个名字"连段1",一个动作实际上是一段动画,

     在这段动画播放的 *某个时间段内* 按下第 2 次 $X$ 就会触发另外一个动作"连段2",我们把从一个动作到下一个动作叫做 *派生*,

     我们姑且先把这个时间段称作 *输入时机*,在输入时机之外的任何输入,以及输入时机之内的任何无法派生出下一个动作的输入都会被无视,有时人们会把动画内"输入时机"之外的时间叫做 *空窗期* (window).

     同样在"连段2"结束前按下第 3 次 $X$ 后会派生出最后一个动作"连段3",等最后一个动作结束了,招式才能算完成,也就进入了 *招式结束* 的状态.

     这是完整使用招式的正常过程,还有因为一些原因(没有进入正确,受到敌人攻击)无法成功派生出下一个动作而提前进入招式结束状态,这种叫做 *招式中断*.

     不过有时候中断招式可以是玩家故意的,因为在没有进入 *招式结束* 状态时, *规则之外的任何输入都是无效的*,

     如果在使用招式时发现敌人马上要攻击过来了,想走位躲避,或者想使用另外一个招式进行格挡,但是这两个招式又无法衔接上,那么没办法,只能吃下这攻击.

     我们把这种处于使用招式中的状态叫做 *连携态*; 在连携态之外的时间内,角色都处于 *自由态*,这状态下角色可以使用任何招式,也可以把它理解为待出招状态.

     什么时候进入连携态,什么时候进入自由态则需要玩家根据怪物的行为和角色状态进行判断,只有对怪物越了解,对自己的武器性能越了解,时机的选择才能更好.


**** 动作值(Motion Value)

     每一个动作都有自己的伤害大小,这个就是动作指.


**** Guard Point

     简称 =GP=,可以理解为完美防御,或者瞬间防御.

     在一些招式动作里面,有若干帧的动画时间会让角色是处于减免伤害的状态,暂且把这几帧叫做 *GP帧* 吧,

     这个状态下可以抵减轻甚至抵消角色受到的 *一次* 攻击,同时也会保持动作 *减少变形* 或者说减少收到伤害的硬直,减少的程度受到 *防御性能* 影响.

     我们会把这种情况说是"把攻击 =GP= 掉",如果硬直很小,角色还能够快速派生招式.

     注意,是一次 =GP= 只能抵消一次攻击,想抵消多段攻击需要进行多次 =GP=.

     因为 =GP= 一次会消耗耐力,耐力不足会 =GP= 失败,所以面对多段攻击最好选择走位躲避,耐力的消耗也会受到 *防御性能* 的影响.

     只有部分武器拥有 =GP= 机制,基本上带盾的武器都有这种机制,盾斧就是一把"通过GP进行快速反击怪物"为卖点的武器,它是一个很好的例子,

     使用 =GP= 就是让 *GP帧* 覆盖怪物攻击到角色的时间点, *GP帧* 的数量是很少的,可能就零点几秒的样子,可以说 =GP= 十分需要玩家看准时机,

     就拿盾斧来说,由于输入延迟的存在,玩家需要适当提前按下触发 =GP= 帧的按键,这增加了盾斧 =GP= 的难度(我也不清楚是不是只有盾斧才是这样的).


**** 斩味

     武器锋利度


*** 武器

**** 盾斧(Charge blade,简称CB)

     盾斧是一把拥有剑模式(Sword mode)和斧模式(Axe mode)两种模式的武器,并且拥有一套能量机制.

     # 补充剑模式和斧模式的图,以及能量瓶图标.

     在不考虑额外因素情况下,能量瓶(phials)的能量 *主要* 来源是通过剑模式的攻击进行积累,

     通过瓶子的图标可以看到能量的积累程度,一共有四种: 白,黄,红和红色闪光,分别对应"零","少量","满"以及"过载".

     # 补充能量瓶图标

     要使用积累的能量,需要先把能量填充进瓶子里面,俗称"装瓶",这个时候能量瓶的图标就发生改变,瓶子由空心变实心.

     在能量过载的时候,剑在一般模式下攻击会出现弹刀情况,因此注意及时装瓶.

     而装好的瓶子只能由斧模式的招式使用.

     所以总体下来盾斧的一套使用流程就是以剑模式的招式负责收集能量,以斧模式的招式使用能量.


***** 基本操作

      本文会使用出招表的形式来学习基本操作,所以先来学习一些要用到的标志:

      $\rightarrow$ 符号用于两个指令之间,表示两个指令之间的衔接;

      $+$ 表示两个指令一起按,比如 $X+A$ 就是 $X$ 键和 $A$ 键一起按,这里的一起按并不要求在同一个时间点按下(当然也可以这么做),而是指最终一起按住,比方说这例子,可以先按住 $X$ 再按住 $A$,这个时间间隔不时固定的,要看动作是如何设定的;

      $(x)$ 括号的内容表示动作名字;

      $=$ 表示最后得到的动作;

      现在可以开始学习盾斧的基本操作了.

****** 一. 剑模式

       剑模式的所有攻击可以积累能量,一旦搜集到能量可以马上通过 $ZR + A$ 进行 $(装瓶)$.

       $ZR(防御)$,防御时间和按住的时间是一样的.

       $收刀时,推动左摇杆 + X = (剑拔刀突进斩)$

       $持刀时,X + A = (剑突进斩)$

       $(剑拔到突进斩/剑突进斩)$ 可以角色在与魔物稍有距离时作为起手技能.

       $X(剑牵制斩) \rightarrow X(剑回斩) \rightarrow X(剑回旋斩)$

       $翻滚后 \rightarrow X = (剑回斩)$

       $长按A后到合适时候松开 = (蓄力二连斩)$

       $(蓄力二连斩) \rightarrow x = (剑回旋斩)$

       $任意剑攻击后 \rightarrow 推动左摇杆 + A = (剑移动斩)$

       $任意剑攻击后 \rightarrow X + A = (盾突刺)$

       $(盾突刺) \rightarrow X + A = (高压力属性解放斩,俗称大解)$,它相当于盾斧的大招, $(大解)$ 过后会把强制把盾斧重置为剑模式.

       (剑移动斩)的后摇会比较大,所谓的前摇/后摇分别就是动作开始的窗口期和动作结束的窗口期,

       可以使用 $(盾突刺)$ 或者 $B$ 指令进行 $(翻滚)$ 来取消后摇,

       不过 $(翻滚)$ 的后摇也很大,因此可以使用盾斧的 $(垫步)$ 来进行替代.

       $任意剑攻击/(装瓶)后 \rightarrow 左右推动左摇杆 + B = (左右垫步)$

       $(垫步) \rightarrow X = (剑回旋斩)$

       $ZR+X = (剑变形斩)$, $(剑变形斩)$ 后武器进入斧模式

       攒能量的思路

       1.(可循环)蓄力二连斩 $\rightarrow$ 剑回旋斩

       2.(可循环)蓄力二连斩 $\rightarrow$ 盾突刺 $\rightarrow$ 蓄力二连斩

****** 二. 斧模式 (Axe mode)

       $收刀时,ZR = 直接进入斧模式,并且进行 (拔刀突进敲打)$

       $持刀时,ZR = (斧变形斩),然后进入剑模式$

       $推动左摇杆 + X = (突进敲打)$

       $X = (斧上捞斩)$

       $(斧上捞斩) \rightarrow X = (斧下斩)$

       $(突进敲打) \rightarrow X(斧上捞斩) \rightarrow X(斧下斩)$

       $X+A = (大解)$

       $A(属性解放斩,俗称一解) \rightarrow A(属性解放斩二,俗称二解) \rightarrow A(大解)$

****** 三. 能量使用

       把能量填充到瓶子后就可以使用能量了,能量有两种用途: *强化武器* 以及 *输出*.

       *武器强化* 分两种: 属性强化状态,俗称开红盾,以及剑强化状态,俗称开红剑,

       这两种强化有依赖关系,必须在红盾状态下才能开红剑.

       \\

       开红盾的操作很简单: $在(大解)抬手时,ZR = 取消大解,消耗所有的瓶子并进入红盾状态$.

       红盾维持的时间和瓶子数量有关,因此基本上是等瓶子满了再开红盾.

       在红盾状态下,角色的防御性能会得到提高,并且武器的一些招式会发生改变:

       斧模式下的 $(一解)$ 和 $(二解)$ 各自消耗一个瓶子;

       以正常操作的方式使用 $(大解)$ 会升级为 $(超高出力属性解放斩,俗称超解)$, $(超解)$ 会一次消耗完剩余的能量瓶,并且造成相应的爆炸伤害;

       当然,红盾状态下也可以强制使用 $(大解)$,在 $(超解)$ 抬手动作到到发电机轰隆响得时,往人物的后方向推动摇杆 + X = $(大解)$, $(大解)$ 消耗一个瓶子.

       消耗瓶子就是能量的第二种用途: *输出*.

       \\

       红剑状态下,任意剑攻击会附着爆炸伤害,不消耗能量,并且不会因为能量过载/武器斩味低而弹刀.

       开红剑也行简单,只有一个前提就是必须在红盾状态下,不管有没有瓶子, $ZR+A(填充)动作起手时, \rightarrow 按住A直到填充进去时松开 = (剑高压属性斩)$.


****** 四. 常用连招和派生

       斧模式下,突进敲打 $\rightarrow$ a = 属性解放斩2

       斧模式下,斧上捞斩 $\rightarrow$ a = 属性解放斩2

       斧模式下,斧下斩 $\rightarrow$ a = 属性解放斩

       (rise新增)斧模式下,斧上捞斩 $\rightarrow$ x+a = 高出力属性解放斩

       斧模式任意攻击 $\rightarrow$ x+a = 高出力属性解放斩

       剑模式下,垫步和剑移动斩可以无限循环,也就是任何剑攻击后 $\rightarrow$ (往角色左或右方向推动摇杆+b $\rightarrow$ 往任意方向推动摇杆+a)循环

       又或者,任何剑攻击后 $\rightarrow$ (往任意方向推动摇杆+a $\rightarrow$ 往角色左或右方向推动摇杆+b)循环

       剑模式下,任何剑攻击后 $\rightarrow$ 往角色背后方向拉到摇杆+a $\rightarrow$ x+a（盾突刺）$\rightarrow$ x+a(高出力属性解放斩)

       (在接盾突刺前可以稍微调整方向?)

****** 五. GP机制

****** 六. 打点控制

       在怪物猎人里面,对于近战武器来说站怪物身边攻击不一定能造成伤害,这取决于攻击是否能命中,而能否命中取决于角色的站位和玩家是否熟悉武器的攻击轨迹,以及招式产生的位移.

       

       盾斧 剑模式 在按下攻击指令前拉动左边摇杆
       
*** 进阶

    学习/分析怪物机制,拆解怪物的AI以及研究如何应对处理.

**** 硬直机制(stun)
