#+title: 前端人员的GIMP
#+date: 2018-11-22
#+index: 前端人员的GIMP
#+tags: GIMP
#+begin_abstract
虽然不太想承认,但是前端人员有时候的确会被叫做切图仔.其实孤身一人的前端人员的确需要会一点切图技能.

我自学时候都是在网上找设计稿来还原的,设计稿有了但是素材得自己动手,我就是因为这个问题才来写这篇文章得.

大部份前端人员都是在 =Windows= 或者 =MacOS= 上使用 =PhotoShop= 来处理这些工作,对于使用 =Linux= 的前端人员就行不通了.

这里我选择了 =GIMP= 做为 =PhotoShop= 的替代品.本人使用的 =GIMP= 版本是 *2.10*.
#+end_abstract

因为基本上都是拿设计稿和素材来进行开发的,只有缺失素材的时候才需要在设计稿上面切图.反正又不是专业做平面设计的,所以个人认为前端人员只要掌握基本的测量(measuring),缩放(resizing)和剪切(cropping)三个技能就可以了,因为测量是要看素材大小,缩放是因为要调整素材大小,而裁剪则是为了获取素材.这三个分别对应: *Measure Tool*, *Scale Tool* 和 *Crop Tool*,此外还需要掌握 *Rulers* 和 *Guides* 的使用.

设计稿主要分两种情况: =PSD= 和 =非PSD=.假如拿到的是良好的 =PSD= 那么并不怎么需要测量工具和裁剪工具,这里的良好是指分层良好,足以让你光看 =layer= 的大小就可以看出你想要的尺寸,在 =GIMP= 里面可以选择 =layer= 后,在菜单栏上按照 =Layer -> Scale Layer= 来观察 =layer= 的原本尺寸,这样的好处就是不需要前端人员手动测量,可以避免误差的发生.如果设计稿是 =非PSD= 或者分层不好的 =PSD=,那么就需要我上面提到的三个技能和两个辅助工具的使用,这种情况是本文的重点.


*** 标尺 (Rulers)

使用辅助线(guides)之前最好先开启标尺,这样就方便地从标尺拖动来新建辅助线.标尺的开启可以在菜单栏里面按照 =View -> Show Rulers= 的路径查找或者使用默认快捷键 =Shift+Ctrl+R= 进行切换.


*** 辅助线 (Guides)

当你拿到的分层不好的 =PSD= 或者 =非PSD= 文件,那么图片的大小就要自己来测量了,使用测量工具以前我们需要辅助线来做为参照. =GIMP= 常用新建辅助线的方式有 =4= 种,你可以在菜单栏里面按照 =Image -> Guides= 这个路径来找到其中 =3= 种,分别是根据位置,百分比和选择来新建,最后一种就是从标尺里面拉出来.

如果想要移除某条辅助线,可以选中辅助线并且拖动会标尺中.

如果想要一次性移除所有辅助线,那么 =Image -> Guides -> Remove all Guides=.

如果只是隐藏所有辅助线, =View -> Show Guides= 或者使用默认快捷键 =Shift+Ctrl+T= 进行切换.

如果你害怕使用某些工具的时候选择有差误,那么辅助线就一定要打好,因为辅助线可以在你选择的时候帮你修正,所以打好辅助线是准确的第一步也是最后一步,而一般来说, =良好的PSD= 设计稿都是打好了辅助线的,所以这点基本不用担心.


*** 测量工具 (Measure Tool)

你可以在 =GIMP= 左边的工具箱里面找到 =Measure Tool= 的图标或者在菜单栏中按照 =Tools -> Measure= 又或者使用默认快捷键 =Shift+M= 进行启用.我们使用测量工具无非就是测量图片的宽和高,如果已经打好了辅助线的画只要在两条辅助线之间拉一条线(暂时叫它测量线)然后在 =GIMP= 的底部状态栏中看长度就可以了.

不过有一点要注意的是测量线一定垂直辅助线,这里有一个使用技巧 *按着 =Ctrl= 然后拉线*,这样 =GIMP= 就会在每 =15= 度的范围内帮你修正.并且测量工具会帮你自动在辅助线上修正起点和终点的定位,不用担心测量的时候差误一两个 =px=,差误是出在建立辅助线的时候.

其实测量工具也可以用来建立辅助线, =Ctrl + Double Click= 在鼠标当前点建立水平的辅助线, =Alt + Double Click= 在鼠标当前点建立垂直的辅助线.


*** 裁剪工具 (Crop Tool)

裁剪工具实际就是移除选择之外的部分,所以保存的时候要注意另外存为,毕竟裁剪工具一个不留神保存错了可是会破坏原来设计稿的.还有一个替代方案就是使用选择工具(Select Tool)加上复制粘贴来进行替代: 选择后 =Ctrl + C=,然后在菜单栏按照 =File -> Create -> From Clipboard= 的路径或者使用默认快捷键 =Shift + Ctrl + V= 粘贴复制的内容到新的图片上.这样就不会因为失误保存而破坏了原来的设计稿,并且选择工具的功能上比裁剪工具更全面,裁剪工具只能裁剪矩形,而选择工具能做到更多.


*** 缩放工具 (Scale Tool)

当图片的大小不符合你的预期的时候可以使用缩放工具来变更图片的尺寸.这个也是可以配合辅助线来使用的.

*** 更高级的玩法

和 =PhotoShop= 一样 =GIMP= 也支持用户自己编写脚本来完成繁琐而重复的工作,不过 =Gimp= 使用的脚本语言是 =Script-Fu= 和 =Python=,其中 =Script-Fu= 就是 =Scheme= 的一个方言,标准是 =R5RS=.除了写脚本,还可以使用 =C= 写插件,写插件没什么了解,花了两个小时左右的时间来体验了一下用 =Script-Fu= 写脚本,整体而言还挺简单的.具体教程请自行看 =GIMP= 的官方文档,至于 =Script-Fu= 的 =GIMP API= 文档,并没有这种东西,不过有 =PDB= (Procedure DataBase),可以菜单栏 =Filters -> Script -> Console= 弹出的对话框里面点击 =Browse= 查看有哪些函数可以使用,本这块我自己也在研究,以后有新发现的话我会单独写.


*** 最后

以前因为 =PhotoShop= 的复杂而被劝退, =GIMP= 的使用还是比较简单的,而且文档也比较友好,上手难度也不太大,还有重要的一点就是 =GIMP= 是开源,免费和全平台的,但是它的简单也侧面说明了它可能没有 =PhotoShop= 那么强大,不过我的话只要功能够用就可以了,而且在 =Linux= 上使用 =GIMP= 比 =PhotoShop= 要方便多了, =GIMP= 应该会作为我的常驻工具之一.
