#+title: About Python
#+date: 2018-06-14
#+index: About Python
#+tags: Python
#+begin_abstract
Something about Python, including books and blogs
#+end_abstract

This is the page about books and blogs for improving your ability to use Python, will be keeping
updating.

这个页面列出了关于 Python 的书,帮助你进一步掌握 Python, 并且会持续更新.

*** Change Log
- 2018-06-14:
  - added three books

    The Python3 Standard Library by Example

    Python Cookbook

    Foundations of Python Network Programming

  - added two blogs

    Python 3 Module of the week 

    A Curious Course on Coroutines and Concurrency

- 2018-07-30:
  - added one blog

    Structure and Interpretation of Computer Programs


*** BOOKS

**** Python Language
- [[https://doughellmann.com/blog/the-python-3-standard-library-by-example/][The Python3 Standard Library by Example]]

  It provides the examples to explain the use of Python 3 standard Library, that are not included
  in the official docs. It is more friendly than the official docs. I recommend you to use this
  book with official docs, because it cannot keep updating in time as official docs does. It is
  from a topic in a blog, you can also read it on the blog (that always be latest).
  The blog is listed below.

  这本书提供了 Python 3 的标准库的示例代码,包含了官方文档所没有的例子,适合与文档结合使用,唯一的缺点就是
  内容的更新跟不上官方文档进度,这本书来源于一个博客的专栏,也可以直接阅读对应的博客.博客已经在下面给出.

- [[http://shop.oreilly.com/product/0636920027072.do][Python Cookbook]]

  If you want some practical recipes, then this book is definitely what you want. It cover a dozen
  topics about core Python language. It can give you a quick improvement in using Python. The goal
  of this book is different from "The Python3 Standard Library by Example", it is not about explaining
  the use of standard library.

  如果你想要一本菜谱的话,这本书就是你想要的.它涵盖了大量关于Python的话题.它可以让你在使用Python上有一个开始的提升.
  跟”The Python3 Standard Library by Example“不同的是,它不是主要讲标准库的使用.

**** Network Programming

- [[https://www.apress.com/us/book/9781430230038][Foundations of Python Network Programming]]

  This book give you a introduction about network programming using Python. If you write Python
  and does not have much knowledge about network programming but want a speed run, then I recommend
  you to read this book. How to read it? Just as fast as you can, there is not many details about
  network programming.

  这本书适合写Python的人用来入门网络编程.如果你写Python并且不怎么了解网络编程,但想来个简单的速通,那么我就推荐你看这
  本书.以你最快的速度读这本书,因为这本书细节不多.


*** BLOGS
- [[https://pymotw.com/3/][Python 3 Module of the Week]]

  This blog is the cause of "The Python3 Standard Library by Example". It always be the latest.

  这个博客就是 "The Python3 Standard Library By Example" 的原因.并且总是最新版本.

- [[http://dabeaz.com/coroutines/][A Curious Course on Coroutines and Concurrency]]

  This article is about coroutines. Very comprehensive, you should check it out.

- [[http://wla.berkeley.edu/~cs61a/fa11/61a-python/content/www/index.html][Structure and Interpretation of Computer Programs]]

  If you want to read SICP but don't know any about Scheme, here is the chance to read it now.
  This is a website all about SICP with Python.

