#+title: 图形学-几何变换
#+date: 2020-06-10
#+status: wd
#+index: 图形学-几何变换
#+tags: Graphics
#+begin_abstract
几何变换是图形学里面的一个重要基础知识点,这主要关于对象的 *缩放,平移以及旋转*,这些都可以通过矩阵来进行描述.

而矩阵的含义就是等同于"映射/变换",所以在了解之前需要先了解一些线性代数的知识,我也不是这方面的专家,就不分享自己微不足道的学习经验了.

实际上如果单纯只是为了应用的话,记住结论就可以了,但是个人认为,如果真的打算与图形学打交道,那么只有理解了为什么才能愉快地与图形学相处,

否者会过的很痛苦.很多参考资料都是直接给出变换的结论,没有推导过程,或者有不完全的推导过程,所以我才下定注意写下自己思考.
#+end_abstract

*** 实际例子

    用一个人 "John Smith" 走路去坐巴士作为演示,通过 *伸缩/平移/旋转* 这三个词进行描述,为了容易理解,我们把 "John Smith" 看作一个长方体,

    场景: John Smith 往他的前方直行到一个路口,左转后继续直行到巴士停靠的位置,最后上车坐车.

    解释:

    - *往他的前方直行* 就是一个 *平移*,直行了多远就是沿着他的方向平移了多远.

    - *左转* 就是一个 *旋转*,向左边方向旋转了多少度,这里假设是90度,通常路口都是直角.

    - *上车坐车* 就是一个 *伸缩*,可能车门的高度不高过 John Smith 的身高,所以 John Smith 要弯下腰降低高度,这样就是沿着身高缩放了.


    如果这个过程要通过数学的方式描述出来,那么就要进入正文了,等了解完以后回这个例子感受以下.


*** 2D变换

    2D 变换和 3D 变换同等重要,并且有一定的联系,先理解 2D 变换有助于理解 3D 变换.

    在 2D 变换中,这里所有的例子都是基于直角坐标系,用矩阵表示该坐标系就是 $\left(\begin{array}{c}1 & 0 \\ 0 & 1\end{array}\right)$.

    这里还需要一位主角: 点 $p$, 它的坐标为 $\left(x_{p}, y_{p}\right)$.

**** 平面平移

     基本的平面平移分两个方向: 沿着 $x$ 轴和沿着 $y$ 轴平移,分别的移动距离是 $d_{x}$ 和 $d_{y}$.

     所以描述 $p$ 的平移是这样的: 先沿着 $x$ 轴方向移动 $d_{x}$,然后沿着 $y$ 轴方向移动 $d_{y}$.

     这里先沿着 $x$ 轴移动 $d_{x}$ 还是先沿着 $y$ 轴移动 $d_{y}$ 都无所谓,到达的最终地点都是 $p^{'}$: $\left(x_{p}^{'}, y_{p}^{'}\right) = \left(x_{p}+d_{x}, y_{p}+d_{y}\right)$.

     用矩阵表示就是这个平移的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ 1 \end{array}\right) = \left(\begin{array}{c}1 & 0 & d_{x} \\ 0 & 1 & d_{y} \\ 0 & 0 & 1\end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p} \\ 1\end{array}\right)$.

     要注意,在3种变换中,只有平移不是线性变换,它是仿射变换.

     这里用函数 $translate(p, d_{x}, d_{y})$ 表示平移.

     这里还有一个有趣的事实,就是 $translate(p, d_{x}, d_{y})$ 后到达 $p^{'}$,如果 $p^{'}$ 再发生一次平移 $translate(p^{'}, dx^{'}, dy^{'})$ 到达 $p^{''}$,这整个过程等于 $translate(p, d_{x} + d_{x}^{'}, d_{y} + d_{y}^{'})$.

     #+BEGIN_SRC elisp

     #+END_SRC

**** 平面伸缩

     和平面平移类似,伸缩也分两个方面: 坐标系的 $x$ 轴变为原来的 $r_{x}$ 倍, 坐标系的 $y$ 轴变为原来的 $r_{y}$ 倍.

     坐标系伸缩后 $p$ 到达 $p_{'}$: $p^{'}$: $\left(x_{p}^{'}, y_{p}^{'}\right) = \left(r_{x}x_{p}, r_{y}y_{p}\right)$.

     用矩阵表示这个伸缩的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'}\end{array}\right) = \left(\begin{array}{c}r_{x} & 0 \\ 0 & r_{y}\end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p}\end{array}\right)$.

     这里用函数 $scale(p, r_{x}, r_{y})$ 表示.

**** 平面旋转

     平面旋转就是坐标系围绕着原点进行旋转,旋转后得到一个新的坐标系,并且 $p$ 到达 $p_{'}$.

     新坐标系的 $y^{'}$ 轴和 $x^{'}$ 轴分别就是原来的 $y$ 和 $x$ 旋转 $\theta$ 得来的.

     不过现在先不这么想,等过了一轮推导后再回来看.

     在 $x$ 轴取一个点 $r$: $\left(1, 0\right)$,从原点出发分别到这个点,根据这条线画一个圆.

     旋转 $\theta$ 度后到达 $r^{'}$: $\left(x_{r}^{'}, y_{r}^{'}\right)$,把这条线 $\vec{or^{'}}$ 看作是三角形的斜边,这条线的长度 $\|\vec{or^{'}}\|$ 为 1.

     再结合一点三角函数可以得出 $x_{r}^{'} = \frac{x_{r}^{'}}{\|\vec{or^{'}}\|} = \cos \theta$ 以及 $y_{r}^{'} = \frac{x_{y}^{'}}{\|\vec{or^{'}}\|} = \sin \theta$,

     所以 $r^{'} = \left(\cos \theta, \sin \theta\right)$.

     接下来再推导 $y$ 轴上的 $\left(0, 1\right)$ 经过旋转后的 $r^{''}$,这里可以直接继续用 $r$ 开始旋转来进行推导,

     $r^{''}$: $\left(x_{r}^{''}, y_{r}^{''}\right)$ 就是 $r$ 旋转 $90 + \theta$ 度后到达的坐标,

     同样结合三角函数可以得出 $x_{r}^{''} = \frac{x_{r}^{''}}{\|\vec{or^{''}}\|} = \cos \left(90+\theta\right)$ 以及 $y_{r}^{''} = \frac{x_{y}^{''}}{\|\vec{or^{''}}\|} = \cos \theta$.

     而 $\cos \left(90+\theta\right) = - \sin \theta$,所以这里也可以看作是从 $\left(0, 1\right)$ 旋转,所以 $r_{''} = \left(-\sin\theta, \cos\theta\right)$.

     回到最开始说到的,本质是坐标轴的旋转,我们得到的 $r^{'}$ 以及 $r^{''}$ 恰好就可以作为表示新坐标系的基向量,

     所以新坐标系的基底就是 $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)$.

     用矩阵表示 $p$ 围绕原点旋转 $\theta$ 度这个过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'}\end{array}\right) = \left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p}\end{array}\right)$.

     这里用函数 $rotate(p, \theta)$ 表示.

**** 综合三种平面变换

     上面三种变换可以通过一个通用的矩阵表示,而实际开发中很多工具都提供了对应的接口,综合起来就是 $\left(\begin{array}{c}a & b & e \\ c & d & f \\ 0 & 0 & 1\end{array}\right)$.

     *通过这个矩阵,可以同时指定平面平移以及平面伸缩,或者同时指定平面平移以及平面旋转.*

     这里用函数 $matrix(a, b, c, d, e, f)$ 表示,实际中不同工具中的参数顺序可能是不一样的,所以这个不用太在意.

**** 拓展思考

     目前提到平面旋转是 $p$ 围绕原点旋转的,那么围绕任意点 $q$: $\left(x_{q}, y_{q}\right)$ 呢?

     可以这么思考,先把 $q$ 设定为新原点 $o^{'}$: $(0, 0)$,也就是旧原点 $o$ 变换到 $o^{'}$,这是一个平面平移.

     在新原点下, $p$ 的新坐标是 $\left(x_{p} - x_{q}, y_{p} - y_{q}\right)$.

     剩下的就是围绕新原点 $o^{'}$ 进行旋转了,同样在新 $x$ 轴上取一个点 $r$: $(1, 0)$,用这根从 $o^{'}$ 到 $r$ 的线条以 $o^{'}$ 为中心画一个圆,

     剩下推导过程就是和之前的一样了,最后得出和以前一样的矩阵 $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)$.

     然后 $p$ 通过矩阵到达 $p^{'}$: $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)\left(\begin{array}{c}x_{p} - x_{q} \\ y_{p} - y_{q}\end{array}\right) = \left(\begin{array}{c} (x_{p} - x_{q})\cos \theta - (y_{p} - y_{q})\sin \theta  \\ (x_{p} - x_{q})\sin \theta + (y_{p} - y_{q})\cos \theta \end{array}\right)$.

     最后再把原点平移回去,$p^{'}$ 的坐标就变成 $\left(\begin{array}{c} (x_{p} - x_{q})\cos \theta - (y_{p} - y_{q})\sin \theta + x_{q} \\ (x_{p} - x_{q})\sin \theta + (y_{p} - y_{q})\cos \theta + y_{q} \end{array}\right)$.

     (这个矩阵写起来有点蛋疼,就不写了).要注意,这个不是线性变换.这个推导最好还是要掌握,说不定就用上了.


*** 3d变换

**** 围绕任意通过原点的轴进行旋转

     这里涉及一些向量的知识
