#+title: 图形学-几何变换
#+date: 2020-06-10
#+status: wd
#+index: 图形学-几何变换
#+tags: Graphics
#+begin_abstract
几何变换是图形学里面的一个重要基础知识点,这主要关于对象的 *缩放,平移以及旋转*,这些都可以通过矩阵来进行描述.

而矩阵的含义就是等同于"映射/变换",所以在了解之前需要先了解一些线性代数的知识,我也不是这方面的专家,就不分享自己微不足道的学习经验了.

实际上如果单纯只是为了应用的话,记住结论就可以了,但是个人认为,如果真的打算与图形学打交道,那么只有理解了为什么才能愉快地与图形学相处,

否者会过的很痛苦.很多参考资料都是直接给出变换的结论,没有推导过程,或者有不完全的推导过程,所以我才下定注意写下自己思考.
#+end_abstract

*** 实际例子

    用一个人 "John Smith" 走路去坐巴士作为演示,通过 *伸缩/平移/旋转* 这三个词进行描述,为了容易理解,我们把 "John Smith" 看作一个长方体,

    场景: John Smith 往他的前方直行到一个路口,左转后继续直行到巴士停靠的位置,最后上车坐车.

    解释:

    - *往他的前方直行* 就是一个 *平移*,直行了多远就是沿着他的方向平移了多远.

    - *左转* 就是一个 *旋转*,向左边方向旋转了多少度,这里假设是90度,通常路口都是直角.

    - *上车坐车* 就是一个 *伸缩*,可能车门的高度不高过 John Smith 的身高,所以 John Smith 要弯下腰降低高度,这样就是沿着身高缩放了.


    如果这个过程要通过数学的方式描述出来,那么就要进入正文了,等了解完以后回这个例子感受以下.


*** 2D变换

    2D 变换和 3D 变换同等重要,并且有一定的联系,先理解 2D 变换有助于理解 3D 变换.

    在 2D 变换中,这里所有的例子都是基于平面版本的正交坐标系,用矩阵表示该坐标系就是 $\left(\begin{array}{c}1 & 0 \\ 0 & 1\end{array}\right)$.

    这里还需要一位主角: 点 $p$, 它的坐标为 $\left(x_{p}, y_{p}\right)$.

**** 平面平移

     基本的平面平移分两个方向: 沿着 $x$ 轴和沿着 $y$ 轴平移,分别的移动距离是 $d_{x}$ 和 $d_{y}$.

     所以描述 $p$ 的平移是这样的: 先沿着 $x$ 轴方向移动 $d_{x}$,然后沿着 $y$ 轴方向移动 $d_{y}$.

     这里先沿着 $x$ 轴移动 $d_{x}$ 还是先沿着 $y$ 轴移动 $d_{y}$ 都无所谓,到达的最终地点都是 $p^{'}$: $\left(x_{p}^{'}, y_{p}^{'}\right) = \left(x_{p}+d_{x}, y_{p}+d_{y}\right)$.

     用矩阵表示就是这个平移的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ 1 \end{array}\right) = \left(\begin{array}{c}1 & 0 & d_{x} \\ 0 & 1 & d_{y} \\ 0 & 0 & 1\end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p} \\ 1\end{array}\right)$.

     要注意,在3种变换中,只有平移不是线性变换,它是仿射变换.

     这里用函数 $translate(p, d_{x}, d_{y})$ 表示平移.

     这里还有一个有趣的事实,就是 $translate(p, d_{x}, d_{y})$ 后到达 $p^{'}$,如果 $p^{'}$ 再发生一次平移 $translate(p^{'}, dx^{'}, dy^{'})$ 到达 $p^{''}$,这整个过程等于 $translate(p, d_{x} + d_{x}^{'}, d_{y} + d_{y}^{'})$.

     #+BEGIN_SRC elisp

     #+END_SRC

**** 平面伸缩

     和平面平移类似,伸缩也分两个方面: 坐标系的 $x$ 轴变为原来的 $r_{x}$ 倍, 坐标系的 $y$ 轴变为原来的 $r_{y}$ 倍.

     坐标系伸缩后 $p$ 到达 $p_{'}$: $p^{'}$: $\left(x_{p}^{'}, y_{p}^{'}\right) = \left(r_{x}x_{p}, r_{y}y_{p}\right)$.

     用矩阵表示这个伸缩的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'}\end{array}\right) = \left(\begin{array}{c}r_{x} & 0 \\ 0 & r_{y}\end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p}\end{array}\right)$.

     这里用函数 $scale(p, r_{x}, r_{y})$ 表示.

**** 平面旋转

     平面旋转就是坐标系围绕着原点进行旋转,旋转后得到一个新的坐标系,并且 $p$ 到达 $p_{'}$.

     新坐标系的 $y^{'}$ 轴和 $x^{'}$ 轴分别就是原来的 $y$ 和 $x$ 旋转 $\theta$ 得来的.

     不过现在先不这么想,等过了一轮推导后再回来看.

     在 $x$ 轴取一个点 $r$: $\left(1, 0\right)$,从原点出发分别到这个点,根据这条线画一个圆.

     旋转 $\theta$ 度后到达 $r^{'}$: $\left(x_{r}^{'}, y_{r}^{'}\right)$,把这条线 $\vec{or^{'}}$ 看作是三角形的斜边,这条线的长度 $\|\vec{or^{'}}\|$ 为 1.

     再结合一点三角函数可以得出 $x_{r}^{'} = \frac{x_{r}^{'}}{\|\vec{or^{'}}\|} = \cos \theta$ 以及 $y_{r}^{'} = \frac{x_{y}^{'}}{\|\vec{or^{'}}\|} = \sin \theta$,

     所以 $r^{'} = \left(\cos \theta, \sin \theta\right)$.

     接下来再推导 $y$ 轴上的 $\left(0, 1\right)$ 经过旋转后的 $r^{''}$,这里可以直接继续用 $r$ 开始旋转来进行推导,

     $r^{''}$: $\left(x_{r}^{''}, y_{r}^{''}\right)$ 就是 $r$ 旋转 $90 + \theta$ 度后到达的坐标,

     同样结合三角函数可以得出 $x_{r}^{''} = \frac{x_{r}^{''}}{\|\vec{or^{''}}\|} = \cos \left(90+\theta\right)$ 以及 $y_{r}^{''} = \frac{x_{y}^{''}}{\|\vec{or^{''}}\|} = \cos \theta$.

     而 $\cos \left(90+\theta\right) = - \sin \theta$,所以这里也可以看作是从 $\left(0, 1\right)$ 旋转,所以 $r_{''} = \left(-\sin\theta, \cos\theta\right)$.

     回到最开始说到的,本质是坐标轴的旋转,我们得到的 $r^{'}$ 以及 $r^{''}$ 恰好就可以作为表示新坐标系的基向量,

     所以新坐标系的基底就是 $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)$.

     用矩阵表示 $p$ 围绕原点旋转 $\theta$ 度这个过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'}\end{array}\right) = \left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p}\end{array}\right)$.

     这里用函数 $rotate(p, \theta)$ 表示.

**** 综合三种平面变换

     上面三种变换可以通过一个通用的矩阵表示,而实际开发中很多工具都提供了对应的接口,综合起来就是 $\left(\begin{array}{c}a & b & e \\ c & d & f \\ 0 & 0 & 1\end{array}\right)$.

     *通过这个矩阵,可以同时指定平面平移以及平面伸缩,或者同时指定平面平移以及平面旋转.*

     这里用函数 $matrix(a, b, c, d, e, f)$ 表示,实际中不同工具中的参数顺序可能是不一样的,所以这个不用太在意.

**** 拓展思考

     目前提到平面旋转是 $p$ 围绕原点旋转的,那么围绕任意点 $q$: $\left(x_{q}, y_{q}\right)$ 呢?

     可以这么思考,先把 $q$ 设定为新原点 $o^{'}$: $(0, 0)$,也就是旧原点 $o$ 变换到 $o^{'}$,这是一个平面平移.

     在新原点下, $p$ 的新坐标是 $\left(x_{p} - x_{q}, y_{p} - y_{q}\right)$.

     剩下的就是围绕新原点 $o^{'}$ 进行旋转了,同样在新 $x$ 轴上取一个点 $r$: $(1, 0)$,用这根从 $o^{'}$ 到 $r$ 的线条以 $o^{'}$ 为中心画一个圆,

     剩下推导过程就是和之前的一样了,最后得出和以前一样的矩阵 $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)$.

     然后 $p$ 通过矩阵到达 $p^{'}$: $\left(\begin{array}{c} \cos\theta & -\sin\theta \\ \sin\theta & \cos\theta \end{array}\right)\left(\begin{array}{c}x_{p} - x_{q} \\ y_{p} - y_{q}\end{array}\right) = \left(\begin{array}{c} (x_{p} - x_{q})\cos \theta - (y_{p} - y_{q})\sin \theta  \\ (x_{p} - x_{q})\sin \theta + (y_{p} - y_{q})\cos \theta \end{array}\right)$.

     最后再把原点平移回去,$p^{'}$ 的坐标就变成 $\left(\begin{array}{c} (x_{p} - x_{q})\cos \theta - (y_{p} - y_{q})\sin \theta + x_{q} \\ (x_{p} - x_{q})\sin \theta + (y_{p} - y_{q})\cos \theta + y_{q} \end{array}\right)$.

     (这个矩阵写起来有点蛋疼,就不写了).要注意,这个不是线性变换.这个推导最好还是要掌握,说不定就用上了.


*** 3d变换

    3D 变换可以想象成是 2D 变换的升级版: 多了一个维度.不过就算这么说,实际上 3D 变换的推导过程要远比 2D 变换的推导复杂很多.

    主角 $p$ 来到 3D 后就变成 $\left(x_{p}, y_{p}, z_{p}\right)$,坐标系变成三维版本的正交坐标系,用矩阵表示就是 $\left(\begin{array}{c}1 & 0 & 0 \\ 0 & 1 & 0 \\ 0 & 0 & 1 \end{array}\right)$.

**** 三维平移

     这个很简单,就是比平面平移多了一个维度,推导过程没什么好说的,用矩阵表示这个平移的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ z_{p}^{'} \\ 1 \end{array}\right) = \left(\begin{array}{c}1 & 0 & 0 & d_{x} \\ 0 & 1 & 0 & d_{y} \\ 0 & 0 & 1 & d_{z} \\ 0 & 0 & 0 & 1 \end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p} \\ y_{z} \\ 1\end{array}\right)$.

**** 三维伸缩

     这个也很简单,同样没什么好说,用矩阵表示这个伸缩的过程就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ z_{p}^{'}\end{array}\right) = \left(\begin{array}{c}r_{x} & 0 & 0 \\ 0 & r_{y} & 0 \\ 0 & 0 & r_{z}\end{array}\right)\left(\begin{array}{c}x_{p} \\ y_{p} \\ z_{p}\end{array}\right)$.

**** 三维旋转

     这个就稍微复杂一点,多了一个维度就多了很多种旋转方式了,和平面旋转不一样在于: 平面旋转是围绕某一个点进行的,而三维旋转是围绕某一条直线进行的.

     所以这里分好几种情况,不过如果能够真正理解平面旋转的推导,这里再只要加一把劲就可以理解了.

***** 围绕 $z$ 轴进行旋转

      *这种围绕某一轴旋转的问题可以统一看做垂直于该轴的平面旋转*,这么一说是不是脑海里面有画像了?

      围绕 $z$ 轴进行旋转就是 $x$ 和 $y$ 轴构成的平面的平面旋转, $p$ 经过旋转后到达 $p^{'}$: $\left(x_{p}^{'}, y_{p}^{'}, z_{p}\right)$.

      没错,围绕 $z$ 轴旋转的话, $p^{'}$ 的 $z$ 分量没有变,再仔细想一下, $x$ 和 $y$ 构成的平面旋转不就是在 2D 变换里面推导的那一个吗?

      假设现在围绕 $z$ 轴旋转 $\theta$ 度,那么这个旋转过程用矩阵表示就是 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ z_{p}^{'} \end{array}\right) = \left(\begin{array}{c} \cos \theta & -sin \theta & 0 \\ \sin \theta & \cos \theta & 0 \\ 0 & 0 & 1 \end{array}\right)\left(\begin{array}{c} x_{p} \\ y_{p} \\ z_{p} \end{array}\right)$.

      既然 $z$ 轴都推导出来了,那么围绕 $x$ 轴以及 $y$ 轴都分别可以开始推导出来.

***** 围绕 $x$ 轴进行旋转

      如同上面的推导,可以快速得出 $p$ 围绕 $x$ 轴旋转 $\theta$ 度后到达 $p^{'}$ 的过程,用矩阵表示 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ z_{p}^{'} \end{array}\right) = \left(\begin{array}{c} 1 & 0 & 0 \\ 0 & \cos \theta & -\sin \theta \\ 0 & \sin \theta & \cos \theta \end{array}\right)\left(\begin{array}{c} x_{p} \\ y_{p} \\ z_{p} \end{array}\right)$.

***** 围绕 $y$ 轴进行旋转

      同理, $p$ 围绕 $y$ 轴旋转 $\theta$ 度后到达 $p^{'}$ 的过程,用矩阵表示 $\left(\begin{array}{c}x_{p}^{'} \\ y_{p}^{'} \\ z_{p}^{'} \end{array}\right) = \left(\begin{array}{c} \cos \theta & 0 & - \sin \theta \\ 0 & 1 & 0 \\ \sin \theta & 0 & \cos \theta \end{array}\right)\left(\begin{array}{c} x_{p} \\ y_{p} \\ z_{p} \end{array}\right)$.

      这些都经过本人手动推导过得,由于写出来就很冗余,所以就省略了,还是推荐大家自己手动推导验证一下.

***** 围绕任意通过原点的轴进行旋转

      这里需要对向量要有一定的了解才能看懂推理过程,至少要先了解向量的一些特性以及向量点积.

      这里也稍微提一下,向量 $\vec{r}$ 是一段有方向的线段,长度叫模长,用 $\|r\|$ ,用单位向量表示方向,单位向量就是长度为1的有向线段(只要线条有一点长度就能看出方向,用1是为了方便计算),用 $\hat{r}$ 表示.

      所以 $\vec{r}$ 可以描述为在 $\hat{r}$ 方向长为 $\|\vec{r}\|$,或者有 $\|\vec{r}\|$ 个 $\hat{r}$,得到关系 $\vec{r} = \|\vec{r}\|\hat{r}$.

      假设现在知道另外一个向量 $\vec{s}$, $\vec{r}$ 在 $\vec{s}$ 上的投影如图所示,它们的夹角为 $\theta$,这可以用 *向量点积* (dot product) 表示它们之间的关系: $\vec{r} \cdot \vec{s} = \|\vec{r}\|\|\vec{s}\|\cos\theta$.

      *补图*

      投影其实就是 $\vec{r}$ 的一个分量,标记为 $\vec{r}_{1}$,投影长度为 $\|\vec{r}\|\cos\theta$,所以 $\vec{r}$ 和 $\vec{s}$ 之间的点积就是 $\vec{r}$ 的分量 $\vec{r}_{1}$ 的模长以及 $\vec{s}$ 的模长的乘积.

      而 $\frac{\vec{r} \cdot \vec{s}}{\|\vec{r}\|\|\vec{s}\|} = \cos\theta$,所以 $\|\vec{r}_{1}\| = \|\vec{r}\|\frac{\vec{r} \cdot \vec{s}}{\|\vec{r}\|\|\vec{s}\|} = \frac{\vec{r} \cdot \vec{s}}{\|\vec{s}\|}$,由于 $\vec{r}_{1}$ 和 $\vec{s}$ 的方向是一样的,所以 $\vec{r}_{1} = \frac{\vec{r} \cdot \vec{s}}{\|\vec{s}\|}\hat{s} = \frac{\vec{r} \cdot \vec{s}}{\|\vec{s}\|}\frac{\vec{s}}{\|\vec{s}\|} = \frac{\vec{r} \cdot \vec{s}}{\|\vec{s}\|^{2}}\vec{s}$.

      求出其中一个分量后再求出另外一个分量就不难了.

      还需要多一个概念: *向量叉积* (cross product),它是用来求出与 $\vec{a}$ 和 $\vec{b}$ 都垂直的向量 $\vec{c}$,像这种垂直于整个平面的向量称为法线向量(normal vector),

      公式如下: $\vec{a} \times \vec{b} = \|vec{a}\|\|\vec{b}\|sin\theta \hat{n}$, 其中 $\theta$ 是 $\vec{a}$ 和 $\vec{b}$ 的夹角, $\hat{n}$ 是 $\vec{c}$ 的单位向量.


      预备概念已经够了,可以开始推导,要确保你能够理解这些,否则是看不懂接下来的内容的了.


      假设现在是 $p$ 围绕从原点到点 $s$: $\left(s_{x}, s_{y}, s_{z}\right)$ 直线旋转 \theta 度到达 $p^{'}$.

      这个问题可以改变一下描述: $p$ 围绕 $\hat{s}$ 方向的轴旋转 $\theta$ 度到达 $p^{'}$.

      研究 $p$ 围绕 $\hat{s}$ 方向的轴旋转需要先找出垂直于该轴的平面,也就是需要找到两个互相垂直的向量,并且这两个向量也要分别和 $\hat{s}$ 垂直.

      这里可以先求出 $p$ 到 $\hat{s}$ 上的投影 $\vec{p_{1}}$,由于 $\vec{p_{1}}$ 是和 $\hat{s}$ 共线的,所以之后 $p$ 围绕 $\hat{s}$ 旋转是不会影响 $\vec{p_{1}}$ 的, *受影响的是 $p$ 的另外一个分量 $\vec{p_{2}}$,这个分量刚好垂直于 $\hat{s}$*.

      为了更加直观表示 $p$ 的分量与 $s$ 的平行以及垂直关系,这里分别用 $\vec{p_{\parallel}}$ 和 $\vec{p_{\perp}}$ 表示 $\vec{p_{1}}$ 和 $\vec{p_{2}}$.

      那么剩下的只要构造出多一个同时垂直于 $\hat{s}$ 以及 $\vec{p_{\perp}}$ 的向量 $\vec{w}$,关于构造 $\vec{w}$ 最方便就是利用 $\hat{s}$ 与 $\vec{p_{\perp}}$ 的90 度夹角的向量叉积求出.

      现在总结一下可以得到的关系:

      $\vec{p} = \vec{p_{\parallel}} + \vec{p_{\perp}}$

      $\vec{p_{\parallel}} = \frac{\vec{p} \cdot \hat{s}}{\|\hat{s}\|^{2}}\hat{s}$, 因为 $\hat{s}$ 是单位向量,所以 $\vec{p_{\parallel}} = \left(\vec{p} \cdot \hat{s}\right)\hat{s}$.

      $\vec{p_{\perp}} = \vec{p} - \left(\vec{p} \cdot \hat{s}\right)\hat{s}$.

      $\vec{w} = \hat{s} \times \vec{p_{\perp}} = \hat{s} \times \vec{p}$, 因为 $\vec{p_{\perp}}$ 和 $\vec{p}$ 处于同一个平面上,所以可以得到这样的关系.

      现在垂直于 $\hat{s}$ 的平面基底找齐了,可以讨论平面旋转了.我们采用 $T\left(\vec{p}\right)$ 表示 $p$ 围绕 $s$ 旋转.

      $T\left(\vec{p}\right) = T\left(\vec{p_{\parallel}} + \vec{p_{\perp}}\right)$,因为 $T\left(\vec{p}\right)$ 是一个线性变换, 所以 $T\left(\vec{p}\right) = T\left(\vec{p_{\parallel}}\right) + T\left(\vec{p_{\perp}}\right)$.

      刚才也有提到过,受到旋转影响的只有 $\vec{p_{\perp}}$, $\vec{p_{\parallel}}$ 在旋转过后还是不变的,所以 $T\left(\vec{p_{\parallel}}\right) = \vec{p_{\parallel}}$, $T\left(\vec{p}\right) = \vec{p_{\parallel}} + T\left(\vec{p_{\perp}}\right)$.

      而 $T\left(\vec{p_{\perp}}\right)$ 就得像平面旋转那样推导某一轴旋转那样,根据下图,

      结合 *向量点积* 可以得出 $T\left(\vec{p_{\perp}}\right) = \cos\theta\vec{p_{\perp}} + \sin \theta$.

      假设 $\vec{p_{\perp}}$ 坐标为 $\left(x_{p}, y_{p}\right)$, $\vec{w}$

***** 拓展思考

      对于围绕没有经过原点的轴 $l$ 进行旋转,其实这个问题和平面围绕任意点旋转是一样的,

      可以先找一条穿过原点并且平行于 $l$ 的直线 $l^{'}$,把 $l$ 平移到 $l^{'}$ 的位置上,或者说把坐标系原点平移到 $l^{'}$ 上.

      然后像之前一样进行推导,最后还原平移.
