** 服务器选用
   个人推荐Debian,因为容易使用,版本选9

** 自己电脑上的准备
   如果你的电脑是Windows10并且支持Linux子系统的话,就用Linux子系统来使用ssh.
   又如果你的电脑上有一个能够上网的Linux虚拟机,那么就在虚拟机里面使用ssh.
   如果都不是,那么到 https://gitforwindows.org/ 下载一个git,打开git可以使用ssh.

***   为了避免链接到服务器的时候输入默认密码和被截取密码,推荐完成这一步

      1. 生成登录密钥
	 在(Linux/git客户端)终端输入ssh-keygen, 然后回车一次,之后会提示 Enter passphrase (empty for no passphrase):
	 你可以输入你自己的口令再回车,该口令用于最后登录服务器;也可以直接回车,这样你登录就不需要输入口令了

      2. 把公钥传送到服务器(这一步需要你输入唯一一次服务器密码)
	 cat ~/.ssh/id_rsa.pub | ssh user@your-server "mkdir ~/.ssh && cat - >> ~/.ssh/authorized_keys"

	 user是登录服务器时候的用户,your-server 是你的服务器地址,可以是ip地址,也可以是域名.

** 登录服务器

   ssh user@your-server

   如果没有设置口令就输入密码,然后回车.
   如果设置了口令就输入口令,然后回车.如果是空口令,就直接回车.

** 登录后安装 shadowsocks
   虽然是同一个终端,不过你现在已经再服务器上面了,所以注意,不要乱操作.

   # 确保 pip 和 git 能够正常运作
   apt-get install python3-pip git

   # 安装最新的 shadowsocks
   pip3 install -U git+https://github.com/shadowsocks/shadowsocks.git@master

   # 运行 shadowsocks

   ssserver -p 端口号 -k 密码 -m 加码方法 -d start

   端口号最好不要选443,选一个冷门一点的,以防被识别.
   密码就是之后客户端要验证的密码.
   加密方法有 aes-256-cfb, rc4-md 和其他.

   官方文档有更多的配置说明
   https://github.com/shadowsocks/shadowsocks/wiki

*** 开启BBR算法,可选,可以有些优化网络
    这个链接有开启bbr的操作,如果你是选Debian 9做服务器系统的话,就直接找“开启bbr”那一节
    https://github.com/iMeiji/shadowsocks_install/wiki/%E5%BC%80%E5%90%AFTCP-BBR%E6%8B%A5%E5%A1%9E%E6%8E%A7%E5%88%B6%E7%AE%97%E6%B3%95


** 客户端
   1. Android https://github.com/shadowsocks/shadowsocks-android/releases
   2. Windows https://github.com/shadowsocks/shadowsocks-windows/releases
