#+title: Warframe伤害计算
#+date: 2018-11-28
#+index: Warframe伤害计算
#+tags: Game Warframe
#+begin_abstract
4年前就玩过一段时间的 =Warframe=,后面由于固定队解散而 =AFK=,本来之前就有回归的意向加上最近登录了 =Nintendo Switch=,所以毫不犹豫地选择了回归,而且玩得还挺开心,这真的得感谢 =Panic Button=.

由于时间长没玩并且随着游戏的不断更新而导致机制变了好多,所以我要复习一下这个游戏伤害机制,复习资料我选择了 =Warframe= 的 =Fandom Wiki=, =fandom= 可以拆分为 =Fan= 和 =dom=,其中 =dom= 是 =kingdom= 里面的一个部分,有国度,国家的意思.

=fan= 当然就是粉丝的意思,所以这个维基资料就是粉丝整理的,并且都是经过玩家们验证的,准确性还是可以的.不过即便如此有空的话最好还是自己动手计算验证资料的准确,这是一个好习惯.
#+end_abstract

*** 基础伤害/物理伤害 (Base Damage)

这游戏有物理伤害和元素伤害两大类,物理伤害类型有 =3= 种: 打击(impact),切割(slash)和穿透(puncture);元素伤害类型有 =4= 种: 热(heat),冻(cold),毒(toxin)和电(electricity),这 =4= 种元素类型又叫做 *基本元素类型*,基本元素类型又可以两两混合为新的元素类型,叫做 *混合元素类型*.

武器的伤害为物理伤害和元素伤害的总和,而物理伤害就是 =3= 种类型的物理伤害的总和,元素伤害就是 =4= 种基本元素类型和混合元素类型的总和.元素伤害有触发机率这种东西,触发机率并不是说有多少机率触发伤害,而是有多少机率触发元素伤害的效果.

其实还有第三大类,叫做 =Unique Damage=,这个不算在基础伤害里面,这也是我 =AFK= 之前没有的,不过这个伤害不占据游戏伤害的主边幅,所以不就说了.


*** 修正 (Modifier)

和大部份其它的游戏一样,基础伤害并不是最终伤害(也就是敌人受到的伤害),要考虑敌人的防御和属性克制之类的因素的影响计算出最终伤害.这些影响因素叫做修正(modifier).这游戏并没有防御和属性克制的说法,不过有对应的有护甲(armor),护盾(shield)和生命值类型(health class/type).

护甲则是影响生命值的扣除,敌人有两种情况:有护甲和无护甲.护甲有很多种类型,不同类型对不同伤害类型有不同程度的增益和减益.生命值类型分两个大类,有护盾和生命(health),有护盾的敌人在受到伤害的时候会先减少护盾的值而不是生命,如果护盾没了就真正计算生命值,注意护甲只会影响伤害对生命的计算,不影响护盾的计算.其中生命又分很多类, =flesh=, =cloned flesh= 等等,不同类型不同伤害类型有不同程度的增益和减益.其实护甲也是生命值类型的一种,不过护甲比较特殊,所以需要单独拿出来说.


*** 伤害计算

计算的时候要考虑敌人是否有护甲,所以有两种情况,

- 无护甲

  #+BEGIN_EXAMPLE
  最终伤害 = 基础伤害 * (1 + 生命值类型修正)
  #+END_EXAMPLE

- 有护甲

  这种情况比较复杂,护甲可以受到一些 =mods= 的影响,比如削弱,

  #+BEGIN_EXAMPLE
  最终伤害 = 基础伤害 * [<(1 + 生命值类型修正) * (1 + 护甲修正)> / <1 + 护甲削减率 * (1 - 护甲修正) / 300>]
  #+END_EXAMPLE

这里的最终伤害是没有发生暴击的情况下的.


*** 暴击

这游戏的暴击机制绝对是一大亮点,在发生了暴击的情况下,最终伤害为未发生暴击的最终伤害乘于暴击修正.

暴击修正受 =4= 个因素影响: 暴击率,暴击倍率,暴击等级和身体修正.

武器本身有一个暴击率,叫做武器初始暴击率.有 =2= 种(还有一种,比较特殊)增加暴击率的 =mods= : 相对增加暴击率的 =mod= 和绝对增加暴击率的 =mod=.

#+BEGIN_EXAMPLE
暴击率 = 武器初始暴击率 * (1 + 用于相对增加暴击率的mod的点数)

暴击率 = 武器初始暴击率 * (1 + 用于相对增加暴击率的mod的点数) + 用于绝对增加暴击率的mod的点数
#+END_EXAMPLE

这游戏的暴击率可以突破 =100%=,不要以为暴击率到了 =100%= 就可以了,因为这样游戏有暴击等级这机制,暴击等级由暴击率决定,暴击率为 =0%= 就表示暴击等级为 =0=, =0%<cirt<=100%= 的暴击等级为 =1=,如此类推.

计算暴击伤害的时候,暴击等级和暴击倍率挂钩.暴击倍率就是发生暴击的时候暴击未发生时候的最终伤害要翻多少倍.

#+BEGIN_EXAMPLE
被mod调整过后的暴击率 = 武器初始暴击倍率 * (1 + 用于增加暴击等级的mod的点数)

最终暴击倍率 = 1 + 暴击等级 * (被mod调整过后的暴击倍率 - 1)
#+END_EXAMPLE

最后还有身体修正,

#+BEGIN_EXAMPLE
爆头伤害 = 发生暴击或者未发生暴击的最终伤害 * 爆头倍率 * (1 + 暴击等级 * (2 * 被mod调整过后的暴击倍率 - 1))
#+END_EXAMPLE

爆头倍率一般是 =2=,也有部分敌人的爆头倍率是 =3=.

