#+title: 自身经历谈懒惰
#+date: 2019-03-05
#+index: 自身经历谈懒惰
#+tags: Life
#+begin_abstract
很多人或多或少会有所谓的懒癌或者拖延症,这里我主要结合自己的生活经历来思考懒惰是什么,为什么会懒惰以及怎么克服它.完全没有任何实验数据以及外部资料支撑,单纯是个人的感悟,也就是完全的民科之谈.

因为我本人也是身患懒癌,所以我才需要写下这些思考,同时也是为了找到"治疗"方法.
#+end_abstract

*** 什么是懒惰

相信大部份人读书的时候都有这样的经历:长假的时候老师布置一大堆作业,大部份人都是先玩了一大部分时间然后再等到上学的前一两天赶作业,甚至有人赶不上了直接放弃;或者平时学习或者工作中经常学习到一般或者工作到一半就走神去干别的.

这种时候别人会对这样的你说,你别这么拖拖拉拉/贪玩好不好.这种情况也出现在我身上,现在想起来与其说是拖拉或者贪玩,不如说是懒惰.那么又怎么解释懒惰呢?

我在网上也看过很多关于懒惰的说法,有一个说法是比较符合用于解释我生活中的一些事情,不过我要稍微改一下,"=懒惰就是倾向于逃避麻烦的想法=",为啥会这么说?

相信大部份玩过"刷子"类游戏的人都会出现过: "好肝啊,肝不动,不想肝啊" 3连感叹,"刷子"游戏的英文叫做 =grinding games=, =grinding= 表示玩家为了自己能够在游戏里面更加强大而执行重复的任务.

这种游戏类型的游玩目标就是让玩家自觉去通过重复"劳动"不停地获得更好装备/得到更高的数值,如果这类型的游戏目标达成要求设置不合理的高,那么就会出现刚刚说的感叹3连,甚至玩家会觉得怎么玩个游戏比上班还辛苦(说的就是你 =Warframe=).

今天并不是来说游戏的,之所以举游戏做为例子那是因为有人会说"读书不见你这么用功,玩游戏就这么勤奋",而事实上有不少人因为游戏和读书一样麻烦而变得不怎么愿意玩游戏,甚至弃坑.当然对于大部份人游戏怎么想也是比读书有趣.

这也是我把"懒惰就是倾向于逃避责任的想法"改正"懒惰就是倾向于逃避麻烦的想法",如果读书不枯燥无聊或者游戏的目标要求不高的话,我想都不会有拖延这种说法了.

之所以说是一种想法,那时因为大脑会在麻烦事情出现的时候让你远离它们,回到老师布置作业的例子,我想大部份人都有过一些一闪而过的心理活动或者挣扎,比如"玩了再说","今天先玩,明天再做","不做了,借别人抄就好",或者边做作业边想着玩,心不在焉.

时间一长,可能连想都不用想了,直接放弃,这个时候可以说懒惰是一种 =思维习惯=,成为习惯后遇到稍微麻烦一点的问题都直接避开了,于是问题就得不到解决,久而久之,人不仅变得懒惰,还容易变得胆小甚至冷漠.这么看来怠惰(Sloth)被天主教列为七宗罪之一也是挺合理的.


*** 为什么会变得懒惰

我想人并不是天生懒惰的,也就是说人并非为逃避麻烦而生的,这一点我已经没有办法通过小孩时候的记忆来解读了,不过我记得自己曾经"勤奋"过,却又没分析过自己为什么会变得懒惰,而现在是个好机会.

其实说人喜欢逃避麻烦,那还不如说人喜欢给自己找麻烦,其实一开始不是叫麻烦.想象以下人类以前没有这么娱乐活动的时候能做的事情有多多少,只有衣食住行,当这些物理上的需求得到满足后,人的精神上就会开始变得空虚,生活总需要一些刺激,人们开始给自己制造问题(这个时候还不是麻烦)自己解决,游戏(不单指电子游戏)就是这样来的.

甚至有人喜欢更加刺激的东西,极限运动.所以说人还是蛮喜欢自虐的,当然这些都是基于人类自愿做的,那么不自愿做的事情呢?其实差不多,对于没有做过的事情,大部份人都不会有什么想法的(除非被别人洗脑这件事多难多难),尝试过后才知道难不难,人就是在这个过程后遍得懒惰的.说了这么多,

其实我想说的是因为耐心,人的耐心是有限的,这也是为什么就算是相比读书乐趣多多的游戏也能劝退玩家,当玩家常年累月重复解决同样的问题时,玩家就会失去耐心,所以一款游戏在内容上没有得到更新的话,它就离死不远了,玩家需要新的难题而不是重复的麻烦,玩家会对旧的难题失去耐心并且会在心理上认为它麻烦,玩家也因此变得懒惰.

由于每个人的耐心不一样,所以有了勤劳的人和懒人的这种区分.可能你会说有很多其它原因导致人变懒,起始我也想过,发现耐心相对其它来说接近根本.


*** 什么克服懒惰

在知道懒惰的原因就可以对症下药了,大部份人在养成懒惰这习惯后就会经常伴随焦虑,因为他们经常因为拖延而害怕错过一些目标.因为懒惰也是一种思维习惯,那么首先做的第一件事情就是摆正心态,保持心态乐观.

其次遇到那些"麻烦"的事情,特别是需要很长时间才能完成的事情,你可以先根据实际情况制订一个计划,如果因为不知道事情的难度或者害怕中途出意外而难以制订计划,那么就在开始的第一刻开始动手,你可以带着"早点完成早点休息"的想法去做.

做这些事情的时候请注意合理休息,不能过劳或者过度休息,一但过劳你的耐心就会被消磨掉,而且精神不足也会导致工作效率下下降,过度休息也可能会因为长时间的舒适导致人失去继续完成工作的动力,所以合理的休息是很重要的,个人认为成年人最好晚上到早上能有 =9= 个小时的睡眠,中午一到两个小时的睡眠.

至于工作时间的短暂休息可以在 =5= 分钟左右,这个过程 *最好* 远离手机或者电脑等会引起你注意的东西,否则之后很难回到工作状态.你可能会质疑:怎么要睡这么长时间,这是我个人觉得最好的睡眠时间,如果晚上可以睡眠 =9= 个小时,中午甚至可以不午睡,当然这个 *因人而异* 了,但一定要确保晚上的睡眠时间可以让你觉得一天都不会累.

除了合理休息以外, *最好* 每天进行适当量的运动以及娱乐的,事实上完全禁欲是不科学的,人是对于那些越接触不到事情就越是想去接触的动物,当人开始了解这些东西后人就会慢慢厌倦,慢慢的就会变得佛系甚至不再接触(那些会导致成瘾并且造成依赖的东西不在讨论范围内).

运动的时间不要过长,可以根据自己的空余时间而定,时间过长会变得难以坚持,可以选择高强度并且减少运动时间的搭配,最好就是中等强度和中长的时间(=30 ~ 60 mins=);至于娱乐方式就很简单了,可以是看一部电影,番剧或者一场游戏,同样时间也不能太长,否则你很容易变得沉迷而影响作息和工作.

如果时间还有多,那么请去提升自己的能力吧,这样以后面对事情就更加得心应手,事情也不再麻烦,你也不做懒惰.

最后总结一下,克服懒惰的关键就是合理安排你的精力,对的,不是时间,合理安排时间只不过是合理安排精力的结果.其实 *很多* 人每天觉得好辛苦那只是因为他们睡的不够而已.
