#+title: About Me
#+date: 2018-5-22
#+STARTUP: logdone

* About Me

  正在努力让自己变得更加充实,但是我说的充实是开心的活着,而不是有多不平凡的经历.正如吉良吉影说"我只是想过平静的生活".

  喜欢的东西大部份都是小众的东西,可能是因为很多东西同质化太严重了吧,小众的东西给人一种眼前一亮的感觉.

  表达能力如你所见,词穷一个,不会修饰,听我说话可能会睡着.

* The stuffs I love

- Emacs (a text editor, not a toy but much funnier than a toy, shipping Emacs Lisp that is the  another funny stuff)

- Programming Language

  - Racket

    An awesome programming language I have ever seen.

  - Python

    A programming language being more and more popular due to big data and AI.

    However, the main reason why I choose it is because of its syntax.

- Linux (a cool operating system, a funny tool like Emacs)

  - Debian, the distribution I use mainly.

  - Ubuntu, a Debian-based Linux Distribution.

  - Linux Mint, a Ubuntu-based Linux Distribution.

- Animes & Mangas

  - =Berserk=
  - =JOJO's Bizarre Adventure=
  - =Fullmetal Alchemist=
  - =Fist of the North Star=
  - =so many others=

- Video Games

- EDM

- Books

  - EOPL (Semantics Engineering Of Programming Language)

    I am working on the exercises.

  - SICP (Structure and Interpretation of Computer Programs)

    The book I will read later.

- Foreign Languages

  - English

    A very useful language I am using, try to improve it.
