#+title: 英语消灭计划-Day2
#+date: 2020-02-23
#+index: 英语消灭计划-Day2
#+tags: English
#+begin_abstract
距离上一次英语消灭进行经是几个月前了,当时还是没有坚持下来,现在要开始重启这个计划了,还是不能小看"积累"的力量.

这次的阅读材料取自于 =VA-11 HALL-A:Cyberpunk Bartender Action=,游戏里的日期是 =Tue 13/12=.
#+end_abstract

*** The Augmented Eye News 1

    Title: *Mass emigration continues as QUINCY reveals new economic adjustments*

    By Kimberly La Valette



    With inflation rates among the highest in the world,

    #+BEGIN_EXAMPLE

    1. inflation, noun

       - the action of inflating,a state of being inflated

       - 通货膨胀, noun

    #+END_EXAMPLE

    constant shortages of basic groceries, and rampant violent crime,

    #+BEGIN_EXAMPLE
    2. shortage, noun, 不足, synonyms: lack, deficit

    3. grocery, noun, 食品杂货店; grocery 是美国的用法, grocery store 等同于 supermarket; grocer 则是英国的用法.

    4. rampant, adjective, 泛滥的,疯狂的, absence of restraint. synonyms: unbounded, unchecked.
    #+END_EXAMPLE

    Glitch City's citizens looks for a better life in other countries.


    QUINCY, however, isn't happy with this.

    #+BEGIN_EXAMPLE
    5. be happy with somebody/something, 对某人/物满意,喜欢某人/物.
    #+END_EXAMPLE


    "They learn in our schools and universities" the Prime Minister said during a talk with The Augmented Eye

    #+BEGIN_EXAMPLE
    6. the Prime Minister, noun, 总理,首相
    #+END_EXAMPLE

    "but they apply what they learn somewhere else and I find it rather insulting."

    #+BEGIN_EXAMPLE
    7. inslut, adjective, 无礼的, synonyms: diss
    #+END_EXAMPLE


    This comes after revealing new economic measures for the city,

    #+BEGIN_EXAMPLE
    8. measure, noun, 措施,方法,程度
    #+END_EXAMPLE

    which most analysts consider to be useless for the current environment.


    "They don't know sh*t" concluded QUINCY.




