#+title: EDM必备乐理教程
#+date: 2021-11-10
#+index: EDM必备乐理教程
#+tags: EDM
#+begin_abstract
# https://www.bilibili.com/video/BV1Rt411L7bC
不懂音乐理论(music theory)也能创作出 =EDM=,但是这样很快就会遇到瓶颈,区别好比在掌握语法和不掌握语法的两种情况下学英语一样,

虽然都可以进行表达,但很明显掌握了语法可以表达的更加精确.

同理掌握了音乐理论可以让自己更加容易创作出更加好的 =EDM=.

而且音乐理论也不仅限于 =EDM=,在其它类型的音乐创作上也可以用得上.

接下来开始学习吧.
#+end_abstract

*** 音乐理论概念

**** 速度以及节奏(Tempo & Rhythm)

     # https://www.sohu.com/a/435823943_728352?sec=wd

     在编写一首曲目前,会先决定曲目的播放速度,这个参数叫做 *速度*,它的单位是 =beats per minute=,

     简称 =BPM=, 中文是每分钟多少拍.

     为了更加明白的理解节奏是什么,先暂且不看它的概念,继续从 =BPM= 里面的"拍"出发:

     *什么是拍(beat)?*

     拍实际上是一个相对的时间单位,比如现实的 1 分钟是一个绝对的时间值,它必定等于 60 秒,

     但拍不像分钟这样的时间单位,1 拍等于多少秒取决于 =Tempo=.

     比如一首曲的速度是 =60 BPM=,那么它的 1 拍的时长(或叫时值)就是 $60 \div 60 = 1$ 秒

     再比如,通常 =EDM= 的速度是 =128 BPM=, 它的一拍的时长大约是 $60 \div 128 \approx 0.46875$ 秒.

     如你所见,同样是 1 拍,但在不同的 =Tempo= 下所对应的时长是不一样的.

     现在可以开始学习什么是 *节奏* 了,所谓的节奏就是对多个长短不定的拍子进行编排,它是曲目的基础,

     在确定速度之后,要做的第一件事情就是确定节奏了,那么问题来了,怎么描述节奏呢?

     这时候我们要学习一个概念,叫做拍号(time signature/meter signature),比如 $1/2$, $2/2$, $2/4$, $3/4$, $4/4$, $9/8$, $\cdots$.

     *拍号并非数学意义上的的分数*, 所以这里面的 $1/2$ 和 $2/4$ 不是一回事, $2/2$ 和 $4/4$ 也同理,如此类推.

     还有另外一种示法可以能更好地与分数进行区分,比如 $3/4$ 可以用 $^{3}_{4}$ 表示.

     为了进一步与分数进行区分,先 *暂且* 把这例子里的 3 称呼为 =top=, 4 称呼为 =bottom=, 而不是叫什么分子分母.

     说了半天,拍号到底怎么解读呢?

     其实很简单,依然以 $^{3}_{4}$ 作为例子,我们会把它读"作每个 *小节* (bar/measure)由 3 个 4 分 *音符* (note)组成".

     要想真正理解它的含义就得想了解什么是小节和什么是音符.

     在西方的音乐体系中,一首曲可以划分为若干个小节,每个小节由若干个拍组成,且而每个小节的拍子数量是一样的.

     不知道你发现了没有,"每个小节由若干个拍组成" 和 "每个小节由若干个 n 分音符组成" 这两个描述似乎揭露了 "拍" 和 "音符" 有某种联系?

     毋庸置疑,拍和音符都是相对的时间概念,而音符的时值是由拍的时值来决定的,我们在确定速度后就能得到 1 拍的时值,然后我们会把这 1 拍的时值作为 "n 分音符" 的时值.

     根据时值长短来划分,音符有很多种:

     时值最大的音符叫做 *全音符* (whole note);

     其次,就是 *2 分音符* (minim/half note),它的时值是全音符的一半;

     往下是 *4 分音符* (crotchet/quarter note),它的时值是 *2 分音符* 的一半;

     往下是 *8 分音符* (quaver/eighth note),它的时值是 *4 分音符* 的一半;

     往下是 *16 分音符* (demiquaver/semiquaver/sixteenth note),它的时值是 *8 分音符* 的一半;

     往下是 *32 分音符* (demisemiquaver/thirty-second note),它的时值是 *16 分音符* 的一半;

     再往下是 *64 分音符* (hemidemisemiquaver/sixty-fourth note),它的时值是 *32 分音符* 的一半.

     可以发现

     

     

     
