#+title: Hello, world!
#+date: 2018-05-24
#+begin_abstract
I describe why I blog with Emacs and Org-Mode
#+end_abstract
#+index: Hello, world!

*This is not my first post, actually.* Now I blog with Org-Mode after being away from Jekyll.
Why not Jekyll? Jekyll is good, but it is annoying for me to install Gem and Jekyll when I use
a new computer or reinstall system. I just want to blog once my Emacs configuration is finished.

*Why Org-Mode Projects?* I had been searched a lot of blogging tools for Emacs. Some of them
are listed on [[https://orgmode.org/worg/org-blog-wiki.html][Blogs and Wikis with Org]]. The o-blog is the tool I want, however, is "old". The
others will require external software or also be "old". I have a thought to write my own static
site generator and also tried it for several times until reading this post,
[[https://www.superloopy.io/articles/2017/blogging-with-org-mode.html][Blogging with Org mode And using Emacs as a build tool]](Oh, how can i miss the "Projects").

*Finally.* After finishing Emacs configuration, I feel comfortable to blog. However, there are
something you need to you know if you want to blog like me. The code from the post I read is not
completely right. As you can see, my blog is simple, the biggest problem is lacking of auto-
generated list of latest posts. However, it is fine for me to live with this, but i will manage
to solve it. I write another post to show some details, just because i don't want to make the post
long.
