:PROPERTIES:
:CUSTOM_ID: h-0ec3df2c-b316-4910-987c-b68b2806986c
:END:
#+title: 阅读源代码的策略
#+date: 2026-01-08
#+index: 阅读源代码的策略
#+tags: coding
#+status: wd
#+options: auto-id:t
#+begin_abstract
"如何正确阅读源代码?" 是本人多年以前的疑问, 在网络上找了很久也没有想要的答案, 因为每个答案都不太一样.

在多年后的今天才想起这个问题, 然而此刻心中已有了一个比较明确的答案.
#+end_abstract

*** 理清楚自己阅读代码的目的
:PROPERTIES:
:CUSTOM_ID: h-fd84d7a4-b422-4b02-ba11-444dc11163c7
:END:

现在想起来每个答案背后不一样是因为回答的人阅读代码的目的不一样, 或者阅读代码的时机不一样.

比如说在工作上发现同事的业务代码有问题, 想要阅读他的代码去解决这个问题;

又比如说对编译原理比较感兴趣, 于是想要通过阅读编译器的源代码来学习编译原理.

因此, *要读懂别人的代码, 总需要有一些前置知识*.

比如第一种情况需要了解业务流程, 第二种情况需要具备一定的编译/解释原理结构的知识;

这两种情况的差别在于阅读门槛, 第二种情况比起第一种情况需要特定领域的专业知识.

我相信大部分人阅读源代码的目的都是为了学习某个领域的专业知识, 然而,

直接通过阅读源代码来掌握专业知识, 很容易会出现为什么这么写的疑问,

即便有意识地去检索, 最后大概会发现会连他人对代码的解释也看得不懂,

就像代码一样, 知识之间也会有依赖, 没有这个知识 $B$ 的前置知识 $A$, 那就理解不了 $B$.

因此, 我是不赞同网络上那么二话不说就让新手阅读源代码的做法, 阅读代码之前得保证新手是业内人士,

我对业内人士的定义是具备该领域内一定的专业知识, 可以达到看得懂这方面代码的水平,

这种情况下去阅读代码才有所收获, 但这么一来阅读代码的目的就变成了学习实践, 加强对知识理论的巩固,

而不是学习知识理论了, 也就是说阅读代码并非学习知识理论的手段.

*** 如何阅读开源项目
:PROPERTIES:
:CUSTOM_ID: h-ed093b79-039b-41c8-85a7-975fe98f763f
:END:

**** 找到项目起点
:PROPERTIES:
:CUSTOM_ID: h-1d6b982f-947b-4c95-acd1-23e2217fcaa8
:END:

通常开源项目都有做版本管理, 比如使用 =git= 做版本管理.

版本管理信息可以给读者提供很有用的信息, 比如想要学习项目中某个功能的实现,

可以使用版本控制工具浏览相关功能源代码的提交历史, 从该文件的第一个提交历史开始阅读.

#+BEGIN_SRC bash
  git log --oneline -- /path/to/file
#+END_SRC

因为功能的第一版实现通常都是最简单的, 阅读起来会比较轻松.

同理, 整个项目的阅读也可以这么做: 从第一版开始阅读.

通常整个项目的第一版可以通过 =git-tag= 来找到.

#+BEGIN_SRC bash
  git tag
#+END_SRC

**** 边阅读边做笔记
:PROPERTIES:
:CUSTOM_ID: h-0c0939bd-7175-4475-9581-acc8c6d71cf4
:END:

大部分开源项目都有着自己的项目结构, 这是开发者们为了提高项目的维护性所产生的结果.

然而, 项目结构对于非项目的开发者来说是陌生的. 有时候你只想阅读某个代码文件中的一个函数 $A$,

但发现 $A$ 调用了另一个函数 $B$, 且 $B$ 本身也调用了另一个函数 $C$, 如此类推有着一系列依赖.

这种情况最好通过笔记来理清楚调用关系, 特别是当这些函数被定义在不同的代码文件中,

如果熟悉作图, 那么可以绘制出调用链; 如果不熟悉, 那么按照调用顺序列出即可.

从调用链中选取想要阅读的函数, 理解函数的定义: 函数的执行流程是怎么样的, 为什么这么写, 等等; 把这些东西记录下来.

做笔记需要达到一个标准: 在隔了一段时间后自己能阅读明白.

这是最低标准, 有更高追求可以尝试把笔记写成供众人阅读的教程, 这往往要求内容通俗易懂.

对于不同专业领域, 做笔记的手法也不同, 比如一些情况下需要专门分析几何关系, 那这特别需要作图理解;

这里只想说明别妄想只用纯文字就像把东西说明白, 文字最大的缺点就是不直观, 因为每个人的知识不同,

同一段话在不同人大脑中的成像可能是不一样的, 把东西准确地转述给他人的最佳方法就是把东西给他.
