#+title: 网络数据传输单位
#+date: 2019-04-03
#+index: 网络数据传输单位
#+tags: Network
#+begin_abstract
今天在机核上看到一篇新闻: 韩国三大电信运营商从4月5日开始提供消费用5G通信服务.为了了解5G有多厉害,我决定了解一下数据传输单位.
#+end_abstract

*注意* 这里我就默认你已经了解计算机的储存单位 =(TB, GB, MB, KB, byte 和 bit)= 等知识.

平时见到的基本都是这几个单位 =Gb/s, MB/s, Mb/s, KB/s, Kb/s, b/s=,就拿 =MB/s= 和 =Mb/s= 来说,两者差了一个大小写,所表达的意思也不一样,很多媒体报到经常因为这个问题而出错.

=MB/s= 表示 =Megabyte/sec= 或者 =Megabyte per second=,有时候会写成 =MBps=,

而 =Mb/s= 表示 =Megabit/sec= 或者 =Megabit per second=,有时候会写成 =Mbit/s= 或者 =Mbps=.

简单来说, =B= 表示字节 =byte=, =b= 表示位 =bit=,这是计算机的储存单位之二,运算关系为:

#+BEGIN_EXAMPLE
1 byte = 8 bit
#+END_EXAMPLE

换成网络传输的说法就是

#+BEGIN_EXAMPLE
1B = 8b
#+END_EXAMPLE

*不同的操作系统对储存单位的进制定义不大一样,比如 =MacOS= 的 =1kb= 就是 =1000 bytes=,而 =Windows= 就是 =1kb= 就是 =1024 bytes=,接下来我会采用 =1024= 做为进制.实际上对于同等兆级的单位来说(比如Mb/s 和 MB/s),不管采取哪种进制结果都是一样*.

那么 =1MB= 就是 =(1024 * 1024)B= 了,也就是 =(1024 * 1024 * 8)b= 了.

一般 =ISP= 会使用 =*b/s= 作为单位,而我们电脑上软件使用的则是 =*B/s= 作为单位,有兴趣的可以自己去观察一下.

可以举个生活例子,我们常说的 =100M= 带宽就是 =100Mb/s= 的下载速度,如果换算成软件使用的单位就是 =(100 / 8)MB/s=,也就是 =12.5 MB/s=,在不计算传输损耗以及断线的情况下,要下载一个 =100m= 的文件,只需要等待 =100m / 12.5 MB/s= 秒就可以了.

而 =100Mb/s= 下载速度就是目前4G时代一个常见的数据, 而5G则是表示可以超过 =10Gb/s=, [[https://en.wikipedia.org/wiki/5G][维基]]上则是写了最大为 =20Gb/s=, 目前看到很多报道都说 =NSA= 阶段到 =SA= 阶段初期就会达到 =1Gb/s=,

按照 =(1 * 1024 / 8) = 128 MB/s= 这个速度来下载一个 =100m= 的文件则只需要 =0.78125s=,如果我没有算错的话这是一个很惊人的速度.

当然5G的实际情况只有到时候才清楚,如果按照这些数据来看的话5G确实可以让 =WEB= 领域得到前所未有的"升级",也许因为这样谷歌才开始通过 =Stadia= 进军游戏产业.

虽然通过计算来看5G的速度很可观,但是价格还是个未知数,即便如此,本人还是对5G的到来表示欢迎和感到兴奋.

