#+title: 英语消灭计划-Day1
#+date: 2019-05-02
#+index: 英语消灭计划-Day1
#+tags: English
#+begin_abstract
从今天开始要拓展自己英语的词汇量了,起始之前很久就想拓展了,只不过没想到用博客这种形式来学习.

有一个准则,由于英语的一词多意的特征,所有笔记都会只介绍示例文本中的单词的当前用法.

今天的示例文本来源于"八方旅人" 中 Primrose 的序章剧情. Primrose's Journal 1-1
#+end_abstract

Ten years ago...

Geoffrey Azelhart was murdered, his death witnessed by his daughter, Primrose.

She has sworn revenge against the three men who committed the deed, and their crow tattoos are burned into her memory.

#+BEGIN_EXAMPLE
1. sworn, past participle swear, transitive verb here.

   to assert or promise emphatically or earnestly.

2. commit, transitive verb here.

   to carry into action deliberately, synonyms for commit: perpetrate.

   carry into: perform,

   deliberately: with full awareness of what one is doing; in a way that is intended or planned.
#+END_EXAMPLE

(Playing ...)

"Even when the blade is held at your heart, faith shall be your shield." -- Words of House Azelhart.

Ten years ago...

???-left: Funny how it works. Isn't it?

???-left: Everything that happens in this world falls into one of two neat little categories.

#+BEGIN_EXAMPLE
3. neat, synonyms: tidy, nice, trim.
#+END_EXAMPLE

???-left: Things one's better off knowing, and things one's better off...not.

???-left: Geoffrey Azelhart, I'm afraid you've been poking your nose into the latter.

Lord Geoffrey: I have only done as my convictions bade me do. I have no regrets.

#+BEGIN_EXAMPLE
4. bade, past tense and participle of bid, to issue an order to: tell
#+END_EXAMPLE

???-right: I thought you might say something like that. You're making this delightfully easy.

Primrose: (Father!)

Primrose: ...!

???-right: Make sure he's dead--and let's leave this place before we're seen.

???-left: ...It's done.

???-neck: .......

(Primrose) I will never forget...

Three men, each marked with the sign of the crow.

One on his left arm...

One on his right...

And the last, on his neck.

Three men. Foul scavengers, just like the bird whose mark they bear.

#+BEGIN_EXAMPLE
5. foul, adjective, being odorous and impure: polluted,

   odorous, adjective, bad smelling,

   impure, not pure

6. scavengers, a person employed to remove dirt and refuse from streets
#+END_EXAMPLE

They took my father from me.

And I will never forget.

(Ending)
