#+title: TODOS
#+date: 2019-5-1
#+STARTUP: logdone

最近终于有时间松口气来做其它事情了,然后发现要做的事情有很多,样样都想做的感觉,为了保证这些事情顺利完成便需要一个合理的 =TODO List=,并且这个列表会一直更新.

=TODO List= 会按照以下原则进行设计:

- 一件最小的 =TODO Item= 为一件事情,最小的 =TODO Item= 也就是没有任何子节点的 =TODO Item=,所有 =TODO Items= 都是按照是时间顺序排序,每个 =Item= 都要标明起始以及结束时间.

- =TODO Item= 的制订方案

  1. 根据事情大小安排

     如果一件事情是一周内不能完成的,那么则需要自己规划选取一周的工作量,把一件事情划分为多周,理由:月(30天)的时间跨度大,不容易掌握进度;天过于精细导致要经常规划计划,对于长期计划而言没有必要.综上所述,周(7天)最为合理;

     如果有突发情况发生,如果突发情况时间不长,1~3天则可以在 =TODO Item= 的下面增加关于突发情况的说明或者 =SubTODO Item=,并且适当减少当周的 =TODO Item= 的内容,如果大于3天则取消原计划,进行重新定制.

     重新定制计划的时候不要删除原计划的内容,用中划线划掉.

     完成 =TODO Item= 的内容所需的时间必须小于或者等于一周,大概平均每天1~3个小时的量, *保证任务能够完成并且不会影响之后的计划(如果有的话)* (这点是保证计划顺利执行的关键,并且不会累),

     如果进度比计划提前可以用空余的时间做其它事情,不建议重新规划之后的 =TODO Items=.

     但是如果真的无法避免超出进度的发生并且已经制订了后面的计划,那没办法只能取消后面的计划并且重新制订,因此建议 *在一周快结束的时候才制订下一个计划*.

     并且每天都要 *针对当天的执行情况进行记录* (很重要).

  2. 根据时间安排

     根据自己的时间选择一件能够完成的事情,比如XX天的假期做一件YY事.



*** TODO-LIST

**** 2019年

     - [ ] 5月
       - [ ] (2-4) =Bash Script= 终结计划: 阅读完 =bash= 的文档,系统地学习一遍.
         - [ ] 2
           - [ ] 每日任务
             - [ ] 30分钟体能锻炼
             - [ ] 增加至少一次 =GitHub= 提交记录
             - [ ] 学习每天5个英语单词以及其用法,并且写下笔记.
           - [ ] 计划任务
