f(x) := (
  if (x < 375 and x > 0) then
     16
  elseif (x >= 375 and x < 1125) then
     0.008 * x + 13
  else
     22
  );

g(x) := (
  if (x < 1125) then
     (2 / 375) * x + 16
  else
     22
  );

plot2d([f(x), g(x)], [x, 0, 1600], [xtics, 0, 75, 1600], [label, ["a", 0, 15.9], ["b", 375, 18.0], ["b", 375, 15.9], ["c", 1125, 21.9]], [xlabel, "viewport-width (px)"], [ylabel, "font-size (px)"], [legend, false], [title, "在 b 点可导(红) VS 不可导(蓝)"]);
