#+title: 线性代数读书随笔
#+date: 2019-12-09
#+status: wd
#+index: 线性代数读书随笔
#+tags: Math
#+begin_abstract
"程序员的数学3线性代数"读书随笔
#+end_abstract
#+macro: linear-algebra 线性代数


*** 一些读后感

    除了数学知识以外,作者的思路也确实很棒,本人受益颇深,

    - 探讨什么是什么的时候就有一个不错的思路:与其直接归纳是什么,不如罗列它的性质,通过性质探究本质.

      比如,车是什么?它能跑,能载人,需要燃料动力等等,这样我们也能大概了解到车是什么了.

      这样还有一个好处就是,从车得到的性质可以得出一些定理,可以把这些定理套用在别的拥有类似性质的事物上.

      有点类似 Duck Typing 的做派,理解一样东西更加通透.

      而实际上作者整一本书都贯彻了这种做法.


*** {{{linear-algebra}}} 的实际用途

    - 解决空间问题: 比如,3D 转化成 2D.
    - 处理多个数值组成的数据组: 同样能够转化为"空间"问题进行处理,把数据描绘成 n 维空间的点.



    {{{linear-algebra}}} 描述空间的语言,所以这本书都是通过这个角度来讲解{{{linear-algebra}}},

    个人更喜欢把这句话的主语和宾语反过来.

*** {{{linear-algebra}}} 的局限性

    用图形打比方就是,{{{linear-algebra}}}只是用来解决平面,直线这些水平,笔直的东西.

    但并非说{{{linear-algebra}}}不能解决曲面,曲线这种问题,在允许的误差范围内,

    可以把曲面或者曲线某一部分放大看作平面或者直线(想象成曲面由无数个平面组成/曲线由无数段直线组成),

    最后把问题近似一下就可以使用{{{linear-algebra}}}来解决了.

*** {{{linear-algebra}}} 的主角

    - 向量

      - 严格定义: 有方向的线,空间上的点;

      - 不严格定义: 排列成一列的数字.

            \begin{equation}
              \left(
                \begin{array}{c}
                  6 \\
                  7 \\
                  8
                \end{array}
              \right)
            \end{equation}

            而这里的每一个数字/元素都叫做分量.有 3 个分量,所以这个向量叫做 3 维向量,如此类推有 n 个分量的向量叫做 n 维向量.

            根据分量的数值类型(实数以及复数)划分,向量分为实向量和复向量.

            如果所有分量都是 0,那么这个向量就叫做 0 向量.

      - *注意*: 向量分行列,没有特别说明下默认就是列向量,否者就是行向量.

            \begin{equation}

              \left(
                \begin{array}{c}
                  6 \\
                  7 \\
                  8
                \end{array}
              \right)^\mathsf{T}

              =

              \left(
                \begin{array}{ccc}
                  6\;7\;8
                \end{array}
              \right)

            \end{equation}

            这个里面的 =T= 表示倒置 (Transpose) ,列向量倒置的结果就是行向量,同样,反过来也是可以的.

      - 运算法则

        - 加法

          只支持同纬度向量之间的加法

          \begin{equation}
            \left(
              \begin{array}{c}
                6 \\
                7 \\
                8
              \end{array}
            \right)

          +

            \left(
              \begin{array}{c}
                3 \\
                2 \\
                1
              \end{array}
            \right)

            =

            \left(
              \begin{array}{c}
                9 \\
                9 \\
                9
              \end{array}
            \right)
          \end{equation}

          遵守交换律,分配律以及结合律.同样的运算规律适用于行向量.

        - 常数(标量)与向量的乘法

          \begin{equation}
            3
            \left(

              \begin{array}{c}
              1 \\
              2 \\
              3
              \end{array}
            \right)

            =

            \left(
              \begin{array}{c}
              3 \\
              6 \\
              9
              \end{array}
            \right)
          \end{equation}

          遵守乘法交换律,结合律以及分配律.同样适用于行向量.

      - 从空间的角度看待向量
        
        
