#+title: Pokemon对战入坑笔记
#+date: 2019-12-17
#+index: Pokemon对战入坑笔记
#+status: wd
#+tags: Pokemon
#+begin_abstract
*首先声名一下,这完全是个人向的笔记,不作为教程,主要记录一些对战所使用到的方法以及思路.*

方法基本都是一些用于计算以及分析的数学方法,没错其实这篇笔记就是我个人用来复习数学的,你可以看作是 Pokemon 版的数学建模.

把数学用在游戏上还是挺有意思的.

由于本人是 PVP 新手,所以难免会有一些错误,有错误欢迎指出.
#+end_abstract

*** 宝可梦对战的思维模式

    对战有点类似于 Rock-Scissor-Paper,也就是我们说的石头剪刀布,俗话猜拳.

    猜拳的玩法思路就是猜(read)对手下一个动作是什么,


*** 培养

**** 努力值分配 (Effect value)

    每一只 Pokemon 的 EV 总和 510,其中有两点是无效的,也就是最大可以使用 508 点.

    分配原则是把 EV 分配到常用的种族值上,这就需要根据 Pokemon 的定位进行分配.

    一般来说 EV 分配还需要考虑很多因素,比如精灵的招式池,队伍构成等等.

    - 普防/特防/双防肉盾

      这种 Pokemon 一般都 HP 防御(Def/SpD)这三个种族值比较常用,分配方法就是尽可能让这两或者三个项分配后的数值接近,理由很简单,

      因为 EV 是固定的,举个例子分配 HP 和普防(Def)的话,最后得到 HP 和 Def 的总和也是固定的(毕竟两个最大只能各项加252 EV),

      $HP + Def = Sum$

      $HP * Def = Eval$ 的 Eval 就是综合耐久的评定标准,值越大综合耐久越高,那么如何确定 HP 和 Def 的值呢?

      其实可以用另外一种角度看上面的关系,

      $Avg * 2 = Sum$

      $(Avg - a) + (Avg + a) = Sum$

      $(Avg - a) * (Avg + a) = Avg^2 - a^2 = Eval$

      HP 与 Def 之间的差距为 2a,从上面可以看出 a 越小评定值越大,为 0 的时候 Eval 就达到最大了,

      所以 HP 与 Def 的差距越小越好(当然前提 HP 和 Def 本身要有一定高度).

      当然 252 分配法是比较极端的做法了,这里只是为了说明方法而已,不用太在意.

      利用数学归纳法也可以证明出双防盾(HP,Def,SpD)的分配也是一样的,具体证明过程就不详细描述了(本人渣渣水平怕出问题).

    - 特殊攻击手

    - 物理攻击手


**** 性格选择


*** 对战前的基础知识

**** 常用术语

     - N 本: 一个精灵带了 N 个本系招式,比如一个水系精灵带了两个水系精灵叫做 2 (水)本某某精灵.

     - 平台与实机: 平台也就是网络对战平台,比如 PokemonShowDown(本体是个网站),实机也就是是用实体游戏机对战,后者是官方玩法.

       前者有自己的规则,比如针对于单打根据精灵使用率进行划分,可以在[[https://zhuanlan.zhihu.com/p/36454866][这里]]了解一下.

**** 对战常用道具

     要了解对战常用道具的效果,同一个精灵带不同的道具背后有着不同的策略,需要预测出对手的策略就要先知道道具的效果.

**** 招式了解

     和对战道具一样,它背后也隐藏不同的策略,每只精灵所能学的招式都不一样,这甚至能决定一只精灵的使用率,

     比如影响精灵的打击面,这是能决定一只精灵好不好用,比如 G8 里面的敏捷虫的速度以及特攻都不错,可惜打击面不行.

     所以它上不了热门的进攻型精灵行列.

**** 天气以及场地效果

**** 精灵特性了解

**** 当代精灵了解

     大概了解所有精灵的速度线,预测出手权

     了解常用精灵的种族值以及招式,这对组成队伍以及估算伤害有帮助.

**** 伤害计算公式
