#+title: Pokemon对战入坑笔记
#+date: 2019-12-17
#+index: Pokemon对战入坑笔记
#+status: wd
#+tags: Pokemon
#+begin_abstract
*首先声名一下,这完全是个人向的笔记,不作为教程,主要记录一些对战所使用到的方法以及思路.*

方法基本都是一些用于计算以及分析的数学方法,没错其实这篇笔记就是我个人用来复习数学的,你可以看作是 Pokemon 版的数学建模.

把数学用在游戏上还是挺有意思的.

由于本人是 PVP 新手,所以难免会有一些错误,有错误欢迎指出.
#+end_abstract

*** 努力值分配

    这里不涉及个体值,种族值以及努力值的概念和计算,主要是讲分配努力值的思路.

    同时也不讲252大法,也就是把其中两项属性拉到最高,然后把剩下的4点加到剩下某一项.

**** 速度

     努力值分配一般首先考虑速度,原因很简单,宝可梦是回合制游戏,出手顺序十分重要,有时候就像枪手之间的对决,双方都是一枪击杀,就看谁快了.

     而在宝可梦里面,只要速度比对方多一点,那么在戏法空间外就必定能比对手先出手(不考虑能力升降的情况),所以速度的努力值只需要够用就好,速度分配有可能会过剩,

     通常只有一种情况需要把速度分配到最高,那就是戏法空间外相同精灵之间内战(不考虑能力升降的情况).

     所以给速度分配努力值的思路是根据选定的超速对象进行分配,而超速对象可以选择该精灵的热门"威胁"进行反制,当然选择"威胁"作为超速对象只是其中一种思路,

     确定超速对象以后就要看给该精灵的速度分配努力值是否划算了,举个例子,我方固执(加攻击减特攻)葱游兵想超速内敛(加特攻减攻击)波克基斯,速度种族分别是65和80,

     在50级的时候,假设速度个体值都达到最高,并且不考虑努力值分配以及道具加成的情况,波克基斯的速度是 $\left(\frac{\left[80 \times 2 + 31 + 0\right] \times 50}{100} + 5\right) \times 1 \approx 100$,

     假设100就是葱游兵超速目标,那么葱游兵的速度应该是101,那么应该给速度分配多少努力值呢?

     $\left(\frac{\left[65 \times 2 + 31 + \frac{ev}{4}\right] \times 50}{100} + 5\right) \times 1 \approx 101$,可以解得如下,

     $ev = ((spd_{target} \div modifier -5) \times 2 - spd_{spec} \times 2 - spd_{iv}) \times 4 = ((101 - 5) \times 2 - 65 \times 2 - 31) \times 4 = 124$.

     但是这里有一个问题,对方波克基斯的速度只需要加8点努力值(速度是102)就可以让葱游兵的速度努力值变成无用功,一般来说波克基斯多少都会加点速度,所以如果是为了超速波克基斯那么个人觉得这努力值不划算,

     不如考虑用其它精灵针对波克基斯,所以尽量不要用给低速精灵分配努力值去和高速精灵抢出手权.再举个例子,仙子伊布也是葱游兵的威胁之一,它的速度种族值是60,这个就可以抢,

     仙子伊布的最大速度是 $\left(\frac{\left[60 \times 2 + 31 + \frac{252}{4}\right] \times 50}{100} + 5\right) \times 1.1 \approx = 123$,而经过计算,我们的葱游兵就需要改性格为急躁并且分配220努力值给速度就能保证比仙子伊布先出手.

     当然我还是觉得分配220点不太划算,毕竟葱游兵除了毒击外没什么能够比较好的反制仙子伊布,特性为妖精皮肤的极速仙子伊布在给特攻分配满努力值后能够一发巨声必杀葱游兵,而反过不一定能行,何况仙子伊布更可能把速度的努力值用到其他地方,比如HP,

     即便时固执性格的葱游兵在分配满攻击后要一发毒击击杀满血仙子伊布也只能等暴击,即便在携带了大葱后暴击率为50%,这样打还是不稳重,考虑到波克基斯也是同样的威胁,不如用另外的精灵针对比较好,速度努力值可以用在其他地方或许会更好,比如防御/特防/HP.

     其实葱游兵是可以用252速度的,最终分配方案由自己决定,这里只是按照反制威胁的思路进行分配.

     你也可以通过搭配顺风,戏法空间这些技能,一些精灵特性或者讲究围巾进行分配来超速威胁对象,这种在戏法空间外比威胁对象速度高一点的速度值叫做理想速度值(Ideal Speed Numbers).

     当然你是不可能100%确定猜到对手精灵的速度情况的,所以不需要纠结要超速过所有情况,这就是为什么尽量不要用低速追高速的原因,因为基本上高速下定决心要超过低速基本上是没什么问题的.

**** 攻击/特攻

**** 防御/特防/HP
