#+TITLE: DarkSalt
#+DATE: 2018-05-24
#+OPTIONS: toc:nil
#+HTML_MATHJAX: path: js/mathjax/es5/tex-mml-chtml.js sale: 1.0

* Introduction:

  这是我的个人网站, 主要用来记录一些学习内容.

  最开始是因为工作原因用来记录一些后端开发相关的内容, 那时候是 =2017= 年.

  在 =2018= 年因身体原因在家休息了一年, 同年年底在思考之后的路时想到到有朝一日开发独立游戏, 于是转行做了前端,

  因为前端的 =WebGL= 和 =WebAssembly= 这两个技术可能对游戏开发的技术有一定的交集, 在 =2019= 年 =4= 月份找到了第一份前端工作,

  至此用来记录前端开发的内容, 同年年底开始尝试学习线性代数, 测试自己是否有能耐学习游戏开发, 结果一发不可收拾,

  用来了几个月时间来把变换, 渲染管线和光照的内容吃得差不多, 基本上把一些书本上的公式的推导过程给还原出来了, 也正因为这样,

  我被后面了解到的 =PBR= 的复杂度吓了一跳, 而且工作内容也开始饱和了, 下班回到出租屋已经没有太多精力去推公式了,

  为了不浪费时间, 索性学习一些其它知识, 这样还能让大脑对知识保持新鲜感, 等这些知识学腻了就可以回去推 =PBR= 的公式了, 这个时候已经是 =2020= 年 =8= 月份了.

  结果这一切换就到了 =2022= 年了, 中间跳了一次槽, 某天发现了对渲染管线中光栅化理解不够, 于是又去读了一本书来加深理解, 因为新公司的工作内容太忙了,

  断断续续地在 =2023= 年的 =12= 月份才读完这本书, 正好赶上公司缩编裁员, 于是在 =2024= 年 =1= 月底拿完赔偿在家休息, 春节过后有尝试过转行,

  就这么折腾了半年, 回过神来已经 =8= 月份了, 又到了思考未来的时候了, 于是我开始尝试学习 =Godot= 的使用, 中途又去拾起了 =PBR= 的学习,

  由于 =PBR= 设计大量微积分和概率论, 所以花了两个月学习数学, 花了一个月推导 =PBR= 的公式, 眨眼已经到了现在的 =2025= 年 =2= 月份,

  在补充玩这些基础后终于可以愉快地学习游戏开发了, 所以之后博客的内容主要是围绕游戏开发来展开了.

  这就是网站记录内容的变迁.

* Most recent articles or updates:

#+INCLUDE: "theindex.inc"
