#+TITLE: DarkSalt
#+DATE: 2018-05-24
#+OPTIONS: toc:nil
#+HTML_MATHJAX: path: js/mathjax/es5/tex-mml-chtml.js sale: 1.0

* Introduction:

  这是我的个人网站, 主要用来记录一些学习内容.

  最开始是因为工作原因用来记录一些后端开发相关的内容, 那时候是 =2017= 年.

  在 =2018= 年因身体原因在家休息了一年, 同年年底在思考之后的路时想到有朝一日会开发独立游戏, 于是在分析一番后转行做了前端,

  因为前端的 =WebGL= 和 =WebAssembly= 这两个技术可能与游戏开发技术有一定的交集, 在 =2019= 年 =4= 月份找到了第一份前端工作,

  至此用来记录前端开发的内容, 同年年底开始尝试学习线性代数, 测试自己是否有能耐学习游戏开发, 多年不接触数学的我被自己惊喜到了: 居然有能力自学数学,

  花了一个月学习完线性代数之后再用了几个月时间把变换, 渲染管线和光照的内容吃得差不多, 基本上把一些书本上的公式的推导过程给还原出来了, 也正因为这样,

  我被之后了解到的 =PBR= 的复杂度吓了一跳, 还需要微积分和概率论的知识, 倒霉的是, 届时的工作内容也开始饱和起来了, 下班回到出租屋已经没有太多精力去推公式了,

  为了不浪费时间, 索性学习一些其它知识, 这样还能让大脑对知识保持新鲜感, 等这些知识学腻了就可以回去推 =PBR= 的公式了, 这个时候已经是 =2020= 年 =8= 月份了.

  结果这一切换就到了 =2022= 年了, 中间还跳了一次槽. 某天发现了对渲染管线中光栅化理解不够, 于是又去读了一本书来加深理解, 因为新公司的工作内容太忙了,

  断断续续地在 =2023= 年的 =12= 月份才读完这本 =250= 多页的书, 个人对这个效率是十分不满的, 因为很多知识在以前就了解过的, 但没办法, 就是没时间没精力去学习.

  正好赶上公司缩编裁员, 于是在 =2024= 年 =1= 月底拿完赔偿在家休息, 其实在半年前就已经收到裁员的小道消息了, 没想到拖了半年才执行.

  最初是打算在裁员后拿着赔偿在家脱产学习个一年后转图形方面的工作.

  之所以转行是因为前端这个圈子的变化越来越快了, 用了几年的工具 $A$ 在来年就被新工具 $B$ 替代,

  打个比方来说, 做前端就有点像宝可梦动画里的小智一样, 这个世代各种满级, 下个世代直接清零, 最后成为有 20 年经验的 10 岁宝可梦大师.

  可能有人会说工具迭代好呀, 这不是说明技术在进步嘛, 然而前端的进步是取决于 =OS= 厂商是否对浏览器开发更多的 =API=,

  可惜的是这些 =WEB= 标准定制者当中为了自己的利益一直不配合标准的推广, 典型的就是 =iOS= 上 =PWA=.

  再还有小程序这种各家大厂圈地产品, 使得前端的开发体验更加差了, 也成为了国内事实上的 =PWA= "标准".

  混乱的工作环境 (指前端框架的"战国时代"), 一眼到头的工作内容和晋升空间, 越来越多的碎片时间, 越少越少的整片时间, 年龄的增长以及对未来的担忧,

  种种因素导致了我比 =2018= 那时更加焦虑了, 在 =2023= 年 =4= 月份才发现身体又出现了一样的问题: 长期失眠, 脱发, 肥胖, 精神萎靡.

  那段时间看到前端代码就有种头晕想吐的感觉, 这不是夸张, 如果你觉得夸张, 那你应该知道有些人对一些食物也会犯恶心, 这是一样的情况.

  所以, 在收到裁员消息时有种如释重负的感觉, 随后计划在半年时间内学习图形学, 再加半年内学习 =Godot/ThreeJS/Blender= 等工具,

  接着转 =3D= 方向的 =WEB= 前端岗, 业余时间开发独立游戏. 还能休息一段时间调养身体, 两全其美.

  当然真正裁员在年底, 所以计划是 =2025= 年初开始转行.

  # 但裁员前夕发生了一件事情, 当时来看是一件喜事, 但现在来看就是灾难, 并且打乱我的计划.

  然而裁员前夕因为一些事情只能让我改变计划, 春节过后不时修的改简历和准备项目, 在网上约面试, 期间还时不时帮家里做几天粗活,

  然而 =24= 年的工作行情并不好, 期间只拿到两个 =Offer=, 然而薪资都比以前低, 其中一个还是 =996=, 想起自己看到代码就头晕, 于是尝试转行,

  当然这个过程并不顺利, 不过我发现了一个很有趣的事实: 其它行业的人似乎对互联网出来的人有成见.

  "做互联网的收入不是很高吗", "怎么被淘汰了", "活该". 虽然没这么说, 但谈话的语气和脸上的表情都出卖了他们.

  # 就这么折腾了半年, 那件喜事变坏事了.

  # 在这件事情上, 我自己都不知道是因为感情而投入, 还是因为投入而产生感情, 不过不管是哪种, 至少有一个都是真的.

  # 是前者的话没办法, 只能伤心一段时间了; 如果是后者, 那么把投入收回的话应该不伤心了,

  # 毕竟没人会心疼自己便宜买的东西丢了, 大不了回头再买一个, 但是贵的就不一样了.

  # 所以, 我只能尝试选择回收之前的投入来找答案了, 如果回收了感觉无所谓, 那么这感情一开始就是错觉,

  # 但是我幻想过好几次有那么一瞬间拿回所有投入, 但心里总有一点不甘, 可能真不是错觉吧;

  # 也有可能没有到真正发生的时候才会觉得不甘吧, 具体我也不清楚, 总之, 就这么度过了 =2= 个月.

  =6= 月份发生了一些不好的事情, 虽早有预料, 但心里还是难受, 就这么一直缓到 =8= 月份才稍微振作起来,

  于是开始尝试学习一下 =Godot= 的使用, 中途又去拾起了 =PBR= 的学习, 由于 =PBR= 涉及大量微积分和概率论的应用,

  所以花了两个月学习数学, 花了一个月推导 =PBR= 的公式, 眨眼已经到了现在的 =2025= 年 =2= 月份,

  在补充完这些基础后终于可以愉快地学习游戏开发了, 所以之后博客的内容主要是围绕游戏开发来展开了.

  这就是网站记录内容的变迁, 希望今年成功转行, 步入业余独游开发的正轨, 在 35 岁之前做出一款能够卖出 10 万份的游戏(原本目标是在 32 岁之前实现的).

* Most recent articles or updates:

#+INCLUDE: "theindex.inc"
