#+title: How to Read and Do Proofs 6th Edition 阅读笔记
#+date: 2025-05-12
#+index: How to Read and Do Proofs 6th Edition 阅读笔记
#+tags: Math
#+status: wd
#+begin_abstract
xxx
#+end_abstract

*** Chapter One: The Truth of It All

真值表

#+caption: 真值表
| A     | B     | A implies B / $\mathbf{A} \Rightarrow \mathbf{B}$ |
|-------+-------+---------------------------------|
| True  | True  | True                            |
| True  | False | False                           |
| False | True  | True                            |
| False | False | True                            |

证明一个命题的本质是:

假定 $\mathbf{A}$ 是 =True=, 尝试以 $\mathbf{A} \Rightarrow \mathbf{B}$ 为 =True= 为目的推断出 $\mathbf{B}$ 为 =True=, 来得出 $\mathbf{A} \Rightarrow \mathbf{B}$,

而 $\mathbf{B}$ 的真值需要以 $\mathbf{A}$ 作为依据, 并非简单的 $\mathbf{A}$ 为 =True= 和 $\mathbf{B}$ 为 =True= 就可以了.

#+begin_quote
其实原文是 "you can assume that A is true; your job is to conclude that B is true",

并没有 "尝试以 $\mathbf{A} \Rightarrow \mathbf{B}$ 为 =True= 为目的" 这一句或类似表达, 这里只是把上下文的信息结合在里面了.

从而强调证明的目的是得出 $\mathbf{A} \Rightarrow \mathbf{B}$ 的真值, 推断出 $\mathbf{B}$ 为 =True= 只是实现目的的手段.

这么一来衍生出了一个疑问: 为什么不通过假设 $\mathbf{A}$ 为 =False= 和推断 $\mathbf{B}$ 为 =True= 来得出 $\mathbf{A} \Rightarrow \mathbf{B}$ 为 =True= 的方式来进行证明呢?

因为根据真值表, 当 $\mathbf{A}$ 为 =False= 时, 不管 $\mathbf{B}$ 是 =True= 还是 =False=, $\mathbf{A} \Rightarrow \mathbf{B}$ 都为 =True=.

只要同时保证 $\mathbf{A}$ 为 =True= 和 $\mathbf{A}$ 和 $\mathbf{B}$ 存在逻辑关系, 就可以让 $\mathbf{A} \Rightarrow \mathbf{B}$ 为 =True= 了, 这样的话证明就变得没必要了.

而当 $\mathbf{A}$ 为 =True= 时, 在以证明 $\mathbf{A} \Rightarrow \mathbf{B}$ 为 =True= 的前提下, $\mathbf{B}$ 只能为 =True=.
#+end_quote

*** 前后向证明法 (The Forward-Backward Method)

前后向证明法是最基本的证明方法, 同时也是所有其它证明方法的基础. 它也被称为直接证明法
